import { test, expect } from '@playwright/test';
import { buildSectionTextColorCss } from '../apps/renderer/src/lib/section-text-color-selectors';
import { scanSectionTokens } from '../apps/renderer/src/lib/scan-section-tokens';

const css = buildSectionTextColorCss('fixture', {
  headingColorVar: 'rgb(10, 20, 30)', bodyColorVar: 'rgb(40, 50, 60)', mutedColorVar: 'rgb(70, 80, 90)',
  subheadingColorVar: 'rgb(45, 55, 65)', eyebrowColorVar: 'rgb(201, 10, 20)',
  cardHeadingColorVar: 'rgb(100, 110, 120)', cardBodyColorVar: 'rgb(130, 140, 150)', cardMutedColorVar: 'rgb(160, 170, 180)',
  badgeBgVar: 'black', badgeTextVar: 'white', badgeBorderVar: 'gray',
  darkContextHeadingVar: 'white', darkContextBodyVar: 'white', darkContextMutedVar: 'white',
});

const mediaCss = buildSectionTextColorCss('media', {
  headingColorVar: 'rgb(255, 255, 255)', bodyColorVar: 'rgb(230, 231, 232)', mutedColorVar: 'rgb(210, 211, 212)',
  subheadingColorVar: 'rgb(240, 241, 242)', eyebrowColorVar: 'rgb(201, 10, 20)',
  cardHeadingColorVar: 'rgb(100, 110, 120)', cardBodyColorVar: 'rgb(130, 140, 150)', cardMutedColorVar: 'rgb(160, 170, 180)',
  badgeBgVar: 'black', badgeTextVar: 'white', badgeBorderVar: 'gray',
  darkContextHeadingVar: 'rgb(250, 250, 250)', darkContextBodyVar: 'white', darkContextMutedVar: 'white',
});

// Generated by Tailwind 3.4.19 for the classes used below. Keeping the
// compiler output here exercises the same escaped arbitrary-value selectors
// emitted in the renderer build; the helper must not depend on a hand-written
// stand-in selector.
const compiledTailwindUtilities = `
.text-\\[color\\:var\\(--token-heading\\)\\] { color: var(--token-heading) }
.text-\\[color\\:var\\(--token-body\\)\\] { color: var(--token-body) }
.text-\\[color\\:var\\(--token-on-dark-body\\)\\] { color: var(--token-on-dark-body) }
.text-\\[color\\:var\\(--token-eyebrow\\)\\] { color: var(--token-eyebrow) }
.text-\\[color\\:var\\(--token-price\\)\\] { color: var(--token-price) }
.hover\\:text-\\[color\\:var\\(--token-eyebrow\\)\\]:hover { color: var(--token-eyebrow) }
@media (min-width: 768px) { .md\\:text-\\[color\\:var\\(--token-price\\)\\] { color: var(--token-price) } }
`;

test('section text fallback CSS remains bounded', () => {
  expect(css.length).toBeLessThan(24_000);
  expect(mediaCss.length).toBeLessThan(24_000);
});

test('explicit foreground roles survive section, card and dark-context fallback rules', async ({ page }) => {
  await page.setContent(`<style>${compiledTailwindUtilities}${css}</style><section data-section-id="fixture" data-style style="--token-eyebrow:rgb(201, 10, 20);--token-price:rgb(20, 201, 30)">
    <p id="body">Body</p>
    <p id="background" style="background-color:var(--token-eyebrow)">Body with background</p>
    <p id="size" class="text-gray-500 text-[color:var(--token-heading-weight)]">Legacy text</p>
    <p id="font-size-and-eyebrow" class="font-[var(--token-heading-weight)] text-[color:var(--token-eyebrow)]">Eyebrow</p>
    <p id="eyebrow" class="text-[color:var(--token-eyebrow)]">Eyebrow</p>
    <h2 id="named-heading" class="section-headline">Named heading</h2>
    <p id="named-subline" class="section-subline">Named subline</p>
    <p id="named-copy" class="cms-section-copy">Named copy</p>
    <p id="named-eyebrow" class="cms-eyebrow">Named eyebrow</p>
    <div data-card><p id="card">Card body</p><p id="card-subline" class="section-subline">Card subline</p><p id="card-eyebrow" class="cms-eyebrow">Card eyebrow</p><p id="price" class="text-[color:var(--token-price)]">Price</p></div>
    <div data-color-context="dark"><p id="dark">Dark body</p><p id="dark-role" style="color:var(--token-eyebrow)">Eyebrow</p></div>
    <p id="inline" style="margin:0;color:var(--token-eyebrow)">Inline</p>
    </section>`);
  await expect(page.locator('#body')).toHaveCSS('color', 'rgb(40, 50, 60)');
  await expect(page.locator('#background')).toHaveCSS('color', 'rgb(40, 50, 60)');
  await expect(page.locator('#size')).toHaveCSS('color', 'rgb(70, 80, 90)');
  await expect(page.locator('#named-heading')).toHaveCSS('color', 'rgb(10, 20, 30)');
  await expect(page.locator('#named-subline')).toHaveCSS('color', 'rgb(45, 55, 65)');
  await expect(page.locator('#named-copy')).toHaveCSS('color', 'rgb(40, 50, 60)');
  await expect(page.locator('#named-eyebrow')).toHaveCSS('color', 'rgb(201, 10, 20)');
  await expect(page.locator('#card')).toHaveCSS('color', 'rgb(130, 140, 150)');
  await expect(page.locator('#card-subline')).toHaveCSS('color', 'rgb(45, 55, 65)');
  await expect(page.locator('#card-eyebrow')).toHaveCSS('color', 'rgb(201, 10, 20)');
  await expect(page.locator('#dark')).toHaveCSS('color', 'rgb(255, 255, 255)');
  for (const id of ['eyebrow', 'font-size-and-eyebrow', 'dark-role', 'inline']) await expect(page.locator(`#${id}`)).toHaveCSS('color', 'rgb(201, 10, 20)');
  await expect(page.locator('#price')).toHaveCSS('color', 'rgb(20, 201, 30)');
  await page.locator('section').evaluate(el => (el as HTMLElement).style.setProperty('--token-eyebrow', 'rgb(5, 6, 7)'));
  await expect(page.locator('#eyebrow')).toHaveCSS('color', 'rgb(5, 6, 7)');
  await expect(page.locator('#price')).toHaveCSS('color', 'rgb(20, 201, 30)');
  await expect(page.locator('#body')).toHaveCSS('color', 'rgb(40, 50, 60)');
});

test('dark contexts win inside cards while named semantic roles stay independent', async ({ page }) => {
  await page.setContent(`<style>${css}</style><section data-section-id="fixture" data-style>
    <div data-color-context="dark">
      <div data-card>
        <h2 id="dark-card-heading">Dark card heading</h2>
        <p id="dark-card-body">Dark card body</p>
        <p id="dark-card-eyebrow" class="cms-eyebrow">Card eyebrow</p>
      </div>
    </div>
  </section>`);
  await expect(page.locator('#dark-card-heading')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(page.locator('#dark-card-body')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(page.locator('#dark-card-eyebrow')).toHaveCSS('color', 'rgb(201, 10, 20)');
});

test('role scan finds nested fallback tokens but ignores text and injected styles', async ({ page }) => {
  await page.setContent(`<section><style>p { color:var(--token-danger) }</style>
    <p style="color:var(--token-card-body,var(--token-body))">Example: var(--token-success)</p>
    <p class="text-[var(--token-eyebrow)]">Eyebrow</p></section>`);
  const tokens = await page.evaluate(`Array.from((${scanSectionTokens.toString()})(document.querySelector('section')))`);
  expect(tokens).toContain('--token-card-body');
  expect(tokens).toContain('--token-eyebrow');
  expect(tokens).not.toContain('--token-danger');
  expect(tokens).not.toContain('--token-success');
});

test('responsive and hover utilities win over section defaults at the active state', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.setContent(`<meta name="viewport" content="width=device-width, initial-scale=1"><style>${compiledTailwindUtilities}${css}</style><section data-section-id="fixture" data-style
    style="--token-price:rgb(20, 201, 30);--token-eyebrow:rgb(201, 10, 20)">
    <p id="hover-only" class="hover:text-[color:var(--token-eyebrow)]">Hover role</p>
    <p id="responsive-only" class="md:text-[color:var(--token-price)]">Responsive role</p>
  </section>`);
  await expect(page.locator('#hover-only')).toHaveCSS('color', 'rgb(40, 50, 60)');
  await expect(page.locator('#responsive-only')).toHaveCSS('color', 'rgb(40, 50, 60)');
  await page.setViewportSize({ width: 1024, height: 844 });
  await expect(page.locator('#responsive-only')).toHaveCSS('color', 'rgb(20, 201, 30)');
  await page.locator('#hover-only').hover();
  await expect(page.locator('#hover-only')).toHaveCSS('color', 'rgb(201, 10, 20)');
});

test('media-safe canonical bindings stay light while on-dark roles remain explicit', async ({ page }) => {
  await page.setContent(`<style>${compiledTailwindUtilities}${mediaCss}</style><section data-section-id="media" data-style
    style="--token-heading:rgb(255, 255, 255);--token-subheading:rgb(240, 241, 242);--token-body:rgb(230, 231, 232);--token-muted:rgb(210, 211, 212);--token-on-dark-heading:rgb(250, 250, 250);--token-on-dark-body:rgb(255, 255, 255);--token-eyebrow:rgb(201, 10, 20)">
      <h1 id="canonical-heading" class="text-[color:var(--token-heading)]">Hero</h1>
      <p id="canonical-body" class="text-[color:var(--token-body)]">Hero copy</p>
      <p id="on-dark" class="text-[color:var(--token-on-dark-body)]">On dark</p>
    </section>`);
  await expect(page.locator('#canonical-heading')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(page.locator('#canonical-body')).toHaveCSS('color', 'rgb(230, 231, 232)');
  await expect(page.locator('#on-dark')).toHaveCSS('color', 'rgb(255, 255, 255)');
});
