// Generated by scripts/sync-section-surface.ts.
// Fallback defaults ensure newly added/reused sections expose every top-level FE data field in the CMS editor.
export const SECTION_EDITOR_FIELD_DEFAULTS: Record<string, Record<string, unknown>> = {
  "hero": {
    "align": "",
    "eyebrow": "",
    "facts": [],
    "image": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlay": "",
    "videoUrl": ""
  },
  "servicesGrid": {
    "badgeText": "",
    "ctaHref": "",
    "ctaIcon": "",
    "ctaLabel": "",
    "manualCards": []
  },
  "processSteps": {
    "badgeText": ""
  },
  "testimonials": {
    "ratingCount": 0,
    "ratingValue": 0
  },
  "faq": {
    "badgeText": "",
    "expandFirst": false
  },
  "ctaBand": {
    "badgeText": ""
  },
  "contact": {
    "badgeText": "",
    "formFields": [],
    "introText": ""
  },
  "portfolio": {
    "badgeText": "",
    "ctaIcon": "",
    "subline": ""
  },
  "team": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "newsPreview": {
    "collectionKey": "",
    "linkHref": "",
    "linkIcon": "",
    "linkLabel": "",
    "subline": ""
  },
  "newsGrid": {
    "collectionKey": "",
    "linkHref": "",
    "linkIcon": "",
    "linkLabel": "",
    "subline": ""
  },
  "galleryGrid": {
    "columns": 3,
    "subline": ""
  },
  "richText": {
    "headline": ""
  },
  "videoEmbed": {
    "badge": "",
    "headline": "",
    "text": "",
    "videoUrl": ""
  },
  "freeText": {
    "headline": ""
  },
  "textImage": {
    "badge": "",
    "items": [],
    "layout": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "collectionHero": {
    "bgPosition": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": ""
  },
  "story": {
    "badge": "",
    "image": "",
    "imageAlt": "",
    "items": [],
    "layout": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "text": ""
  },
  "shopProductGrid": {
    "tenantId": ""
  },
  "shopProductDetail": {
    "_slug": "",
    "tenantId": ""
  },
  "shopCheckout": {
    "code": "",
    "error": false,
    "paypalUrl": "",
    "stripeUrl": "",
    "success": false,
    "sumupUrl": "",
    "valid": false
  },
  "shopFeaturedProducts": {
    "categorySlug": "",
    "mode": "",
    "productIds": "",
    "tenantId": ""
  },
  "shopCategoryOverview": {
    "tenantId": ""
  },
  "floristHero": {
    "bgImage": "",
    "bgPosition": "",
    "imagePosition": ""
  },
  "weddingFloristry": {
    "overlayOpacity": 0
  },
  "fitnessHero": {
    "bgImage": "",
    "bgPosition": "",
    "imagePosition": ""
  },
  "programGrid": {
    "ctaHref": "",
    "ctaIcon": "",
    "ctaLabel": "",
    "services": []
  },
  "trainerProfiles": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "trialSessionCta": {
    "imagePosition": "",
    "overlay": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "locationHero": {
    "align": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "videoUrl": ""
  },
  "availabilityCta": {
    "imagePosition": "",
    "overlay": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "floorPlanOverview": {
    "badge": "",
    "items": [],
    "layout": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "galleryMoodboard": {
    "columns": 3
  },
  "hostTeam": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "heroHandwerk": {
    "badgeIcon": "",
    "badgeStarsIcon": "",
    "badgeText": "",
    "bgColor": "",
    "bgImage": "",
    "bgImageMobile": "",
    "bgMode": "",
    "bgPosition": "",
    "bgPositionMobile": "",
    "headline": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "trustItems": [],
    "trustStripColor": ""
  },
  "heroEcommerce": {
    "badgeIcon": "",
    "badgeStarsIcon": "",
    "badgeText": "",
    "bgColor": "",
    "bgImage": "",
    "bgImageMobile": "",
    "bgMode": "",
    "bgPosition": "",
    "bgPositionMobile": "",
    "headline": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "trustItems": [],
    "trustStripColor": ""
  },
  "embed": {
    "config": "",
    "maxWidth": 0,
    "provider": ""
  },
  "noticeBanner": {
    "bgColor": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "textColor": ""
  },
  "socialProofBar": {
    "bgStyle": ""
  },
  "statsCounter": {
    "badge": "",
    "subline": ""
  },
  "featureShowcase": {
    "reversed": false
  },
  "logoMarquee": {
    "headline": "",
    "items": [],
    "subline": ""
  },
  "collectionList": {
    "showDate": false,
    "showExcerpt": false,
    "showImage": "",
    "sortBy": ""
  },
  "verticalTimeline": {
    "bgColor": "",
    "lineColor": "",
    "textColor": ""
  },
  "beforeAfterSlider": {
    "aspectRatio": "",
    "bgColor": "",
    "textColor": ""
  },
  "horizontalScrollShowcase": {
    "panelHeight": 0
  },
  "cinematicHero": {
    "align": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "videoUrl": ""
  },
  "immersiveCtaBanner": {
    "imagePosition": ""
  },
  "popup": {
    "showMode": "",
    "triggerDelayMs": 0
  },
  "glowHero": {
    "bgImage": "",
    "bgPosition": ""
  }
};
