// Generated by scripts/sync-section-surface.ts.
// Fallback defaults ensure newly added/reused sections expose every top-level FE data field in the CMS editor.
export const SECTION_EDITOR_FIELD_DEFAULTS: Record<string, Record<string, unknown>> = {
  "hero": {
    "align": "",
    "backgroundImage": "",
    "eyebrow": "",
    "facts": [],
    "image": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlay": "",
    "overlayColor": "",
    "trustStripColor": "",
    "videoUrl": ""
  },
  "servicesGrid": {
    "badgeText": ""
  },
  "processSteps": {
    "badgeText": "",
    "subline": ""
  },
  "faq": {
    "badgeText": "",
    "expandFirst": false,
    "subline": ""
  },
  "ctaBand": {
    "badgeText": "",
    "ctaSecondary": {
      "label": "",
      "href": ""
    }
  },
  "contact": {
    "badgeText": "",
    "formFields": [],
    "introText": "",
    "mapEmbedUrl": "",
    "showMap": false
  },
  "map": {
    "address": "",
    "mapEmbedUrl": ""
  },
  "portfolio": {
    "badgeText": "",
    "ctaIcon": "",
    "items": [],
    "subline": ""
  },
  "team": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "newsPreview": {
    "collectionBasePath": "",
    "collectionKey": "",
    "columns": 3,
    "limit": 0,
    "linkHref": "",
    "linkIcon": "",
    "linkLabel": "",
    "linkPrefix": "",
    "showDate": false,
    "showExcerpt": false,
    "showImage": "",
    "subline": ""
  },
  "newsGrid": {
    "collectionBasePath": "",
    "collectionKey": "",
    "columns": 3,
    "limit": 0,
    "linkHref": "",
    "linkIcon": "",
    "linkLabel": "",
    "linkPrefix": "",
    "showDate": false,
    "showExcerpt": false,
    "showImage": "",
    "subline": ""
  },
  "galleryGrid": {
    "columns": 3,
    "subline": ""
  },
  "richText": {
    "headline": "",
    "html": "",
    "text": ""
  },
  "legalContent": {
    "content": ""
  },
  "videoEmbed": {
    "badge": "",
    "headline": "",
    "text": "",
    "videoUrl": ""
  },
  "freeText": {
    "headline": "",
    "html": "",
    "text": ""
  },
  "textImage": {
    "backgroundImage": "",
    "badge": "",
    "badgeText": "",
    "bgImage": "",
    "imageSrc": "",
    "imageUrl": "",
    "layout": "",
    "media": ""
  },
  "collectionHero": {
    "backgroundImage": "",
    "bgPosition": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "story": {
    "backgroundImage": "",
    "badge": "",
    "bgImage": "",
    "image": "",
    "imageAlt": "",
    "imageSrc": "",
    "imageUrl": "",
    "items": [],
    "layout": "",
    "media": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "text": ""
  },
  "shopProductGrid": {
    "_isSectionPreview": "",
    "tenantId": ""
  },
  "shopProductDetail": {
    "_slug": "",
    "catalogPath": "",
    "tenantId": ""
  },
  "shopCart": {
    "checkoutPath": "",
    "continueShoppingPath": ""
  },
  "shopCheckout": {
    "code": "",
    "error": false,
    "paypalUrl": "",
    "requirePhone": "",
    "retryWithNewIdempotencyKey": "",
    "showCompanyField": false,
    "stripeUrl": "",
    "success": false,
    "sumupUrl": "",
    "tenantId": "",
    "thankYouPath": "",
    "valid": false
  },
  "shopThankYou": {
    "continueShoppingPath": "",
    "ctaLabel": "",
    "orderNumberLabel": 0
  },
  "shopFeaturedProducts": {
    "categorySlug": "",
    "mode": "",
    "productIds": "",
    "tenantId": ""
  },
  "shopCategoryOverview": {
    "tenantId": ""
  },
  "floristHero": {
    "bgImage": "",
    "bgPosition": "",
    "imagePosition": ""
  },
  "weddingFloristry": {
    "overlayOpacity": 0
  },
  "additionalLocations": {
    "badgeText": ""
  },
  "fitnessHero": {
    "bgImage": "",
    "bgPosition": "",
    "imagePosition": ""
  },
  "programGrid": {
    "ctaHref": "",
    "ctaIcon": "",
    "ctaLabel": "",
    "services": []
  },
  "courseSchedule": {
    "badgeText": ""
  },
  "trainerProfiles": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "membershipPlans": {
    "badgeText": "",
    "cards": []
  },
  "trialSessionCta": {
    "imagePosition": "",
    "overlay": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "studioAmenities": {
    "badgeText": "",
    "cards": []
  },
  "locationHero": {
    "align": "",
    "backgroundImage": "",
    "badgeText": "",
    "bgImage": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "trustItems": [],
    "trustStripColor": "",
    "videoUrl": ""
  },
  "availabilityCta": {
    "imagePosition": "",
    "overlay": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "locationPackages": {
    "badgeText": "",
    "cards": []
  },
  "amenitiesGrid": {
    "badgeText": "",
    "cards": []
  },
  "floorPlanOverview": {
    "backgroundImage": "",
    "badge": "",
    "badgeText": "",
    "bgImage": "",
    "imageSrc": "",
    "imageUrl": "",
    "items": [],
    "layout": "",
    "media": "",
    "secondaryCta": {
      "label": "",
      "href": ""
    }
  },
  "galleryMoodboard": {
    "columns": 3
  },
  "locationAccess": {
    "address": "",
    "mapEmbedUrl": ""
  },
  "hostTeam": {
    "badgeText": "",
    "membersHeadline": "",
    "stats": [],
    "storyHeadline": "",
    "storyImage": "",
    "storyText": "",
    "values": [],
    "valuesHeadline": ""
  },
  "nextMatchHero": {
    "badge": "",
    "badgeText": "",
    "bgImage": "",
    "matches": "",
    "players": "",
    "rows": [],
    "subline": "",
    "tiers": ""
  },
  "matchSchedule": {
    "awayLogo": "",
    "awayTeam": "",
    "badge": "",
    "bgImage": "",
    "competition": "",
    "dateLabel": "",
    "eyebrow": "",
    "homeLogo": "",
    "homeTeam": "",
    "image": "",
    "players": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "rows": [],
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "tiers": "",
    "venue": ""
  },
  "leagueTable": {
    "awayLogo": "",
    "awayTeam": "",
    "badge": "",
    "bgImage": "",
    "competition": "",
    "dateLabel": "",
    "eyebrow": "",
    "homeLogo": "",
    "homeTeam": "",
    "image": "",
    "matches": "",
    "players": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "tiers": "",
    "venue": ""
  },
  "teamRoster": {
    "awayLogo": "",
    "awayTeam": "",
    "badge": "",
    "bgImage": "",
    "competition": "",
    "dateLabel": "",
    "eyebrow": "",
    "homeLogo": "",
    "homeTeam": "",
    "image": "",
    "matches": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "rows": [],
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "tiers": "",
    "venue": ""
  },
  "sponsorsWall": {
    "awayLogo": "",
    "awayTeam": "",
    "badge": "",
    "bgImage": "",
    "competition": "",
    "dateLabel": "",
    "eyebrow": "",
    "homeLogo": "",
    "homeTeam": "",
    "image": "",
    "matches": "",
    "players": "",
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "rows": [],
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "venue": ""
  },
  "editorialHero": {
    "badgeText": "",
    "hideImageOnMobile": "",
    "image": "",
    "imageFit": "",
    "layout": "",
    "mobileImageMode": "",
    "subline": "",
    "variant": ""
  },
  "zigzagShowcase": {
    "startRight": ""
  },
  "statsCounter": {
    "badge": "",
    "badgeText": "",
    "subline": ""
  },
  "bentoGrid": {
    "badgeText": "",
    "cards": []
  },
  "comparisonCardsPro": {
    "badgeText": "",
    "cards": []
  },
  "galleryPro": {
    "badgeText": "",
    "categories": []
  },
  "timeline": {
    "badgeText": ""
  },
  "immersiveCtaBanner": {
    "imagePosition": ""
  },
  "heroHandwerk": {
    "backgroundImage": "",
    "badgeIcon": "",
    "badgeStarsIcon": "",
    "badgeText": "",
    "bgColor": "",
    "bgImage": "",
    "bgImageMobile": "",
    "bgMode": "",
    "bgPosition": "",
    "bgPositionMobile": "",
    "headline": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "trustItems": [],
    "trustStripColor": ""
  },
  "heroEcommerce": {
    "backgroundImage": "",
    "badgeIcon": "",
    "badgeStarsIcon": "",
    "badgeText": "",
    "bgColor": "",
    "bgImage": "",
    "bgImageMobile": "",
    "bgMode": "",
    "bgPosition": "",
    "bgPositionMobile": "",
    "headline": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "trustItems": [],
    "trustStripColor": ""
  },
  "embed": {
    "config": "",
    "maxWidth": 0,
    "provider": ""
  },
  "noticeBanner": {
    "primaryCta": {
      "label": "",
      "href": ""
    },
    "secondaryCta": {
      "label": "",
      "href": ""
    },
    "subline": "",
    "tone": ""
  },
  "comparisonTable": {
    "badgeText": "",
    "subline": ""
  },
  "socialProofBar": {
    "bgStyle": ""
  },
  "featureShowcase": {
    "backgroundImage": "",
    "badgeText": "",
    "bgImage": "",
    "ctaPrimary": {
      "label": "",
      "href": ""
    },
    "imageSrc": "",
    "imageUrl": "",
    "media": "",
    "reversed": false
  },
  "logoMarquee": {
    "headline": "",
    "items": [],
    "subline": ""
  },
  "collectionList": {
    "itemsPerPage": [],
    "pageSize": "",
    "paginate": "",
    "pagination": "",
    "searchPlaceholder": "",
    "showDate": false,
    "showExcerpt": false,
    "showImage": "",
    "showSearch": false,
    "sortBy": ""
  },
  "instagramFeed": {
    "sourceTenantSlug": ""
  },
  "beforeAfterSlider": {
    "aspectRatio": ""
  },
  "horizontalScrollShowcase": {
    "panelHeight": 0
  },
  "cinematicHero": {
    "align": "",
    "backgroundImage": "",
    "badgeText": "",
    "bgImage": "",
    "imageEffect": "",
    "imageEffectIntensity": 0,
    "overlayColor": "",
    "overlayOpacity": 0,
    "trustItems": [],
    "trustStripColor": "",
    "videoUrl": ""
  },
  "proofWall": {
    "stats": [],
    "testimonials": ""
  },
  "popup": {
    "showMode": "",
    "triggerDelayMs": 0
  },
  "bookingWidget": {
    "ctaHref": "",
    "tenantId": ""
  },
  "bookingSlotPicker": {
    "ctaHref": "",
    "tenantId": ""
  },
  "bookingDateRange": {
    "ctaHref": "",
    "tenantId": ""
  },
  "availabilityCalendar": {
    "ctaHref": "",
    "tenantId": ""
  },
  "resourceBookingShowcase": {
    "ctaHref": "",
    "tenantId": ""
  },
  "bookingCtaPro": {
    "ctaHref": "",
    "tenantId": ""
  },
  "serviceTabs": {
    "badgeText": ""
  },
  "priceCalculator": {
    "badgeText": ""
  },
  "offerMatcher": {
    "badgeText": ""
  },
  "jobListings": {
    "badgeText": "",
    "emptyText": ""
  },
  "ctaSplit": {
    "badgeText": "",
    "reversed": false,
    "subline": ""
  },
  "openingStatus": {
    "badgeText": "",
    "closedLabel": "",
    "note": "",
    "openLabel": ""
  },
  "teamSpotlight": {
    "badgeText": ""
  },
  "faqContactSplit": {
    "badgeText": "",
    "whatsapp": ""
  },
  "glowHero": {
    "bgImage": "",
    "bgPosition": ""
  },
  "contactForm": {
    "badgeText": "",
    "formEnabled": false,
    "formFields": [],
    "headline": "",
    "introText": "",
    "mapEmbedUrl": "",
    "showMap": false,
    "subline": "",
    "submitLabel": ""
  },
  "textBlock": {
    "content": "",
    "headline": "",
    "html": "",
    "text": ""
  }
};
