/**
 * Style definitions for each industry + style combination.
 * Each style overrides CSS custom properties that Tailwind reads via var().
 * The "classic" style per industry uses the default values from tailwind.config.
 */

export type StyleConfig = {
  label: string;
  description: string;
  cssVars: Record<string, string>;
};

export type IndustryStyles = {
  label: string;
  styles: Record<string, StyleConfig>;
};

export const INDUSTRY_STYLES: Record<string, IndustryStyles> = {
  tradesman: {
    label: 'Handwerk',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Vertrauenswürdig, professionell, bewährt',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 20px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': 'rgba(255,255,255,1)',
          '--style-accent-glow': '0 0 30px rgba(243, 156, 18, 0.2)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(13,33,55,0.9) 0%, rgba(13,33,55,0.7) 50%, rgba(13,33,55,0.5) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#64748b',
          '--style-badge-bg': 'rgba(26, 82, 118, 0.05)',
          '--style-badge-border': 'rgba(26, 82, 118, 0.1)',
          '--style-divider': '1px solid rgba(0,0,0,0.06)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, clean, großzügig',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.5rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.04em',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#fafafa',
          '--style-text-primary': '#18181b',
          '--style-text-secondary': '#71717a',
          '--style-badge-bg': 'transparent',
          '--style-badge-border': 'rgba(0,0,0,0.12)',
          '--style-divider': '1px solid rgba(0,0,0,0.04)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Kräftig, dynamisch, auffällig',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.05em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.15)',
          '--style-card-border': '3px solid #0d2137',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '6px 6px 0 rgba(243,156,18,0.4)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(13,33,55,0.97) 0%, rgba(13,33,55,0.8) 50%, transparent 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f1f5f9',
          '--style-text-primary': '#0d2137',
          '--style-text-secondary': '#475569',
          '--style-badge-bg': '#f39c12',
          '--style-badge-border': '#f39c12',
          '--style-badge-text': '#0d2137',
          '--style-divider': '3px solid #0d2137',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  restaurant: {
    label: 'Restaurant',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, hochwertig, einladend',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.875rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 50px rgba(57, 34, 18, 0.10)',
          '--style-card-border': '1px solid rgba(57, 34, 18, 0.10)',
          '--style-card-bg': '#fffaf2',
          '--style-accent-glow': '0 0 36px rgba(183, 99, 47, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(30,18,12,0.92) 0%, rgba(68,37,22,0.72) 58%, rgba(30,18,12,0.45) 100%)',
          '--style-section-bg': '#fffaf2',
          '--style-section-bg-alt': '#f4eadc',
          '--style-text-primary': '#28160f',
          '--style-text-secondary': '#806957',
          '--style-text-muted': '#806957',
          '--style-accent': '#b7632f',
          '--style-brand': '#7e4023',
          '--style-badge-bg': 'rgba(126, 64, 35, 0.10)',
          '--style-badge-border': 'rgba(126, 64, 35, 0.16)',
          '--style-badge-text': '#7e4023',
          '--style-divider': '1px solid rgba(57,34,18,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Editorial, reduziert, food-fokussiert',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.75rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(18, 18, 18, 0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.52) 0%, rgba(0,0,0,0.18) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f6f5f0',
          '--style-text-primary': '#181713',
          '--style-text-secondary': '#777267',
          '--style-text-muted': '#777267',
          '--style-accent': '#6b7a3c',
          '--style-brand': '#4d5a36',
          '--style-badge-bg': 'transparent',
          '--style-badge-border': 'rgba(18,18,18,0.14)',
          '--style-badge-text': '#4d5a36',
          '--style-divider': '1px solid rgba(18,18,18,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Kontrastreich, plakativ, event-tauglich',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.18)',
          '--style-card-border': '3px solid #19130f',
          '--style-card-bg': '#fff8e8',
          '--style-accent-glow': '7px 7px 0 rgba(255, 82, 45, 0.35)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(20,13,10,0.96) 0%, rgba(20,13,10,0.76) 54%, transparent 100%)',
          '--style-section-bg': '#fff8e8',
          '--style-section-bg-alt': '#ffdf57',
          '--style-text-primary': '#19130f',
          '--style-text-secondary': '#5f5046',
          '--style-text-muted': '#5f5046',
          '--style-accent': '#ff5230',
          '--style-brand': '#19130f',
          '--style-badge-bg': '#ff5230',
          '--style-badge-border': '#ff5230',
          '--style-badge-text': '#fff8e8',
          '--style-divider': '3px solid #19130f',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  hotel: {
    label: 'Hotel',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Boutique, ruhig, hochwertig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 60px rgba(15, 30, 50, 0.08)',
          '--style-card-border': '1px solid rgba(15, 30, 50, 0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 36px rgba(26, 58, 92, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(12,24,42,0.93) 0%, rgba(25,48,72,0.72) 55%, rgba(12,24,42,0.44) 100%)',
          '--style-section-bg': '#f7f8fb',
          '--style-section-bg-alt': '#eef0f5',
          '--style-text-primary': '#0f1d2e',
          '--style-text-secondary': '#4b5c72',
          '--style-text-muted': '#6b7a8d',
          '--style-accent': '#1a3a5c',
          '--style-brand': '#1a3550',
          '--style-badge-bg': '#1a3a5c',
          '--style-badge-border': '#15304e',
          '--style-badge-text': '#ffffff',
          '--style-divider': '1px solid rgba(15,30,50,0.10)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Urban, klar, editorial',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.75rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(15, 23, 42, 0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.52) 0%, rgba(0,0,0,0.18) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f5f6f9',
          '--style-text-primary': '#101827',
          '--style-text-secondary': '#4b5563',
          '--style-text-muted': '#6b7280',
          '--style-accent': '#1e3a5f',
          '--style-brand': '#1e3a5f',
          '--style-badge-bg': '#1e3a5f',
          '--style-badge-border': '#193250',
          '--style-badge-text': '#ffffff',
          '--style-divider': '1px solid rgba(15,23,42,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Gross, kontrastreich, resortartig',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.18)',
          '--style-card-border': '3px solid #0f1d2e',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '7px 7px 0 rgba(15,29,46,0.42)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(10,20,38,0.96) 0%, rgba(10,20,38,0.76) 54%, transparent 100%)',
          '--style-section-bg': '#f0f2f7',
          '--style-section-bg-alt': '#0f1d2e',
          '--style-text-primary': '#0f1d2e',
          '--style-text-secondary': '#4b5c72',
          '--style-text-muted': '#5e6e82',
          '--style-accent': '#0f1d2e',
          '--style-brand': '#0f1d2e',
          '--style-badge-bg': '#0f1d2e',
          '--style-badge-border': '#0f1d2e',
          '--style-badge-text': '#ffffff',
          '--style-divider': '3px solid #0f1d2e',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  tourism: {
    label: 'Tourismus',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Regional, naturnah, einladend',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.875rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(31, 73, 54, 0.10)',
          '--style-card-border': '1px solid rgba(31, 73, 54, 0.10)',
          '--style-card-bg': '#fbfaf1',
          '--style-accent-glow': '0 0 36px rgba(76, 133, 87, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(19,48,38,0.92) 0%, rgba(45,91,67,0.68) 56%, rgba(19,48,38,0.40) 100%)',
          '--style-section-bg': '#fbfaf1',
          '--style-section-bg-alt': '#e9f0df',
          '--style-text-primary': '#183226',
          '--style-text-secondary': '#667765',
          '--style-badge-bg': '#d7e8b8',
          '--style-badge-border': '#d7e8b8',
          '--style-badge-text': '#3f642f',
          '--style-divider': '1px solid rgba(31,73,54,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Klar, hell, destinationsfokussiert',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.75rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(15, 23, 42, 0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(16,36,54,0.58) 0%, rgba(16,36,54,0.20) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f0f5f4',
          '--style-text-primary': '#102436',
          '--style-text-secondary': '#66757d',
          '--style-badge-bg': '#dcefed',
          '--style-badge-border': '#dcefed',
          '--style-badge-text': '#245b5d',
          '--style-divider': '1px solid rgba(15,23,42,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Kampagne, Outdoor, plakativ',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.18)',
          '--style-card-border': '3px solid #102436',
          '--style-card-bg': '#fff7d6',
          '--style-accent-glow': '7px 7px 0 rgba(255, 184, 61, 0.42)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(16,36,54,0.96) 0%, rgba(16,36,54,0.74) 54%, transparent 100%)',
          '--style-section-bg': '#fff7d6',
          '--style-section-bg-alt': '#ffb83d',
          '--style-text-primary': '#102436',
          '--style-text-secondary': '#5d6b72',
          '--style-badge-bg': '#ffb83d',
          '--style-badge-border': '#ffb83d',
          '--style-badge-text': '#102436',
          '--style-divider': '3px solid #102436',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  salon: {
    label: 'Salon',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Weich, hochwertig, Beauty-orientiert',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(98, 46, 74, 0.10)',
          '--style-card-border': '1px solid rgba(98, 46, 74, 0.10)',
          '--style-card-bg': '#fff7fb',
          '--style-accent-glow': '0 0 36px rgba(194, 82, 138, 0.20)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(54,24,43,0.92) 0%, rgba(105,55,78,0.68) 56%, rgba(54,24,43,0.40) 100%)',
          '--style-section-bg': '#fff7fb',
          '--style-section-bg-alt': '#f7e8ef',
          '--style-text-primary': '#321827',
          '--style-text-secondary': '#7b6472',
          '--style-text-muted': '#7b6472',
          '--style-accent': '#c2528a',
          '--style-brand': '#7a2c55',
          '--style-badge-bg': '#f3c7dc',
          '--style-badge-border': '#f3c7dc',
          '--style-badge-text': '#7a2c55',
          '--style-divider': '1px solid rgba(98,46,74,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Clean, editorial, Studio-Feeling',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.75rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(24, 24, 27, 0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(24,20,28,0.58) 0%, rgba(24,20,28,0.20) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8f4f6',
          '--style-text-primary': '#18141c',
          '--style-text-secondary': '#746b72',
          '--style-text-muted': '#746b72',
          '--style-accent': '#a3527a',
          '--style-brand': '#6d4058',
          '--style-badge-bg': '#f1e3eb',
          '--style-badge-border': '#f1e3eb',
          '--style-badge-text': '#6d4058',
          '--style-divider': '1px solid rgba(24,24,27,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Barber, Nail, Beauty-Kampagne',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.18)',
          '--style-card-border': '3px solid #18141c',
          '--style-card-bg': '#fff0f7',
          '--style-accent-glow': '7px 7px 0 rgba(255, 74, 151, 0.35)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(24,20,28,0.96) 0%, rgba(24,20,28,0.74) 54%, transparent 100%)',
          '--style-section-bg': '#fff0f7',
          '--style-section-bg-alt': '#ff4a97',
          '--style-text-primary': '#18141c',
          '--style-text-secondary': '#655b62',
          '--style-text-muted': '#655b62',
          '--style-accent': '#ff4a97',
          '--style-brand': '#18141c',
          '--style-badge-bg': '#ff4a97',
          '--style-badge-border': '#ff4a97',
          '--style-badge-text': '#fff0f7',
          '--style-divider': '3px solid #18141c',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  wedding: {
    label: 'Hochzeit',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Romantisch, elegant, zeitlos',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '2rem',
          '--style-heading-weight': '300',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0.02em',
          '--style-section-spacing': '6rem',
          '--style-card-shadow': '0 12px 40px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 40px rgba(180,140,120,0.15)',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(20,15,10,0.4) 0%, rgba(20,15,10,0.2) 50%, rgba(20,15,10,0.5) 100%)',
          '--style-section-bg': '#fffcfa',
          '--style-section-bg-alt': '#f9f5f2',
          '--style-text-primary': '#2c2420',
          '--style-text-secondary': '#7a6b60',
          '--style-badge-bg': 'rgba(180,140,120,0.08)',
          '--style-badge-border': 'rgba(180,140,120,0.15)',
          '--style-badge-text': '#8b6f5c',
          '--style-divider': '1px solid rgba(180,140,120,0.15)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, clean, editorial',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0.25rem',
          '--style-radius-lg': '0.5rem',
          '--style-radius-full': '0.25rem',
          '--style-card-radius': '0.25rem',
          '--style-button-radius': '0',
          '--style-heading-weight': '200',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.15em',
          '--style-section-spacing': '8rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(0,0,0,0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f5f5f5',
          '--style-text-primary': '#1a1a1a',
          '--style-text-secondary': '#666666',
          '--style-badge-bg': 'transparent',
          '--style-badge-border': 'rgba(0,0,0,0.15)',
          '--style-badge-text': '#1a1a1a',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Dramatisch, kontrastreich, statement',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.05em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '6px 6px 0 rgba(0,0,0,0.2)',
          '--style-card-border': '2px solid #1a1a1a',
          '--style-card-bg': '#fafafa',
          '--style-accent-glow': '5px 5px 0 rgba(200,160,60,0.4)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(0,0,0,0.92) 0%, rgba(0,0,0,0.6) 50%, transparent 100%)',
          '--style-section-bg': '#fafafa',
          '--style-section-bg-alt': '#f0ece8',
          '--style-text-primary': '#0a0a0a',
          '--style-text-secondary': '#4a4a4a',
          '--style-badge-bg': '#c8a03c',
          '--style-badge-border': '#c8a03c',
          '--style-badge-text': '#0a0a0a',
          '--style-divider': '2px solid #1a1a1a',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  photography: {
    label: 'Fotografie',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Elegant, galerie-inspiriert, bildlastig',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '2rem',
          '--style-heading-weight': '300',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '6rem',
          '--style-card-shadow': '0 12px 40px rgba(0,0,0,0.08)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 30px rgba(0,0,0,0.08)',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 50%, rgba(0,0,0,0.4) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f7f7f5',
          '--style-text-primary': '#1a1a1a',
          '--style-text-secondary': '#6b6b6b',
          '--style-badge-bg': 'rgba(0,0,0,0.04)',
          '--style-badge-border': 'rgba(0,0,0,0.08)',
          '--style-badge-text': '#1a1a1a',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Monochrom, editorial, magazin-typografisch',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '200',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.12em',
          '--style-section-spacing': '8rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(0,0,0,0.1)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f0f0f0',
          '--style-text-primary': '#0a0a0a',
          '--style-text-secondary': '#555555',
          '--style-badge-bg': 'transparent',
          '--style-badge-border': 'rgba(0,0,0,0.2)',
          '--style-badge-text': '#0a0a0a',
          '--style-divider': '1px solid rgba(0,0,0,0.1)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Dunkel, cinematic, high-contrast',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0.25rem',
          '--style-radius-lg': '0.5rem',
          '--style-radius-full': '0.25rem',
          '--style-card-radius': '0.25rem',
          '--style-button-radius': '0',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.03em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 20px 60px rgba(0,0,0,0.3)',
          '--style-card-border': '1px solid rgba(255,255,255,0.1)',
          '--style-card-bg': '#1a1a1a',
          '--style-accent-glow': '0 0 40px rgba(255,200,100,0.2)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 100%)',
          '--style-section-bg': '#111111',
          '--style-section-bg-alt': '#1a1a1a',
          '--style-text-primary': '#f5f5f5',
          '--style-text-secondary': '#a0a0a0',
          '--style-text-muted': '#666666',
          '--style-border-strong': 'rgba(255,255,255,0.2)',
          '--style-border-light': 'rgba(255,255,255,0.1)',
          '--style-bg-subtle': '#1a1a1a',
          '--style-badge-bg': 'rgba(255,200,100,0.15)',
          '--style-badge-border': 'rgba(255,200,100,0.3)',
          '--style-badge-text': '#ffc864',
          '--style-divider': '1px solid rgba(255,255,255,0.1)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  medical: {
    label: 'Aerzte & Praxen',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Serioes, ruhig, vertrauenswuerdig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(15, 76, 92, 0.10)',
          '--style-card-border': '1px solid rgba(15, 76, 92, 0.10)',
          '--style-card-bg': '#f7fcfb',
          '--style-accent-glow': '0 0 36px rgba(82, 168, 176, 0.20)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(8,47,61,0.92) 0%, rgba(15,76,92,0.68) 56%, rgba(8,47,61,0.40) 100%)',
          '--style-section-bg': '#f7fcfb',
          '--style-section-bg-alt': '#e6f3f1',
          '--style-text-primary': '#0f2f3a',
          '--style-text-secondary': '#63777a',
          '--style-badge-bg': '#d5eeeb',
          '--style-badge-border': '#d5eeeb',
          '--style-badge-text': '#0f4c5c',
          '--style-divider': '1px solid rgba(15,76,92,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Klar, hell, patientenorientiert',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '0.75rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '500',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '7rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(15, 35, 48, 0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(12,45,62,0.58) 0%, rgba(12,45,62,0.20) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f1f7f8',
          '--style-text-primary': '#102436',
          '--style-text-secondary': '#68777f',
          '--style-badge-bg': '#e2f2f4',
          '--style-badge-border': '#e2f2f4',
          '--style-badge-text': '#0f5d6b',
          '--style-divider': '1px solid rgba(15,35,48,0.08)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Praegnant, technisch, facharzt-tauglich',
        cssVars: {
          '--style-radius-sm': '0',
          '--style-radius-md': '0',
          '--style-radius-lg': '0',
          '--style-radius-full': '0',
          '--style-card-radius': '0',
          '--style-button-radius': '0',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '8px 8px 0 rgba(0,0,0,0.18)',
          '--style-card-border': '3px solid #0b1f33',
          '--style-card-bg': '#eefafa',
          '--style-accent-glow': '7px 7px 0 rgba(94, 234, 212, 0.40)',
          '--style-hero-overlay': 'linear-gradient(to right, rgba(11,31,51,0.96) 0%, rgba(11,31,51,0.74) 54%, transparent 100%)',
          '--style-section-bg': '#eefafa',
          '--style-section-bg-alt': '#5eead4',
          '--style-text-primary': '#0b1f33',
          '--style-text-secondary': '#526570',
          '--style-badge-bg': '#5eead4',
          '--style-badge-border': '#5eead4',
          '--style-badge-text': '#0b1f33',
          '--style-divider': '3px solid #0b1f33',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  realestate: {
    label: 'Immobilien',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Seriös, vertrauensvoll, hochwertig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 24px rgba(0,0,0,0.08)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 24px rgba(30, 64, 110, 0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,30,55,0.92) 0%, rgba(15,30,55,0.6) 60%, transparent 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f4f7fa',
          '--style-text-primary': '#1a2536',
          '--style-text-secondary': '#5a6a7a',
          '--style-badge-bg': 'rgba(30, 64, 110, 0.06)',
          '--style-badge-border': 'rgba(30, 64, 110, 0.12)',
          '--style-badge-text': '#1e406e',
          '--style-divider': '1px solid rgba(0,0,0,0.06)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, clean, zeitgemäß',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.03em',
          '--style-section-spacing': '6rem',
          '--style-card-shadow': '0 2px 12px rgba(0,0,0,0.04)',
          '--style-card-border': '1px solid rgba(0,0,0,0.04)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(10,20,40,0.85) 0%, rgba(10,20,40,0.4) 100%)',
          '--style-section-bg': '#fafbfc',
          '--style-section-bg-alt': '#ffffff',
          '--style-text-primary': '#111827',
          '--style-text-secondary': '#6b7280',
          '--style-badge-bg': '#f3f4f6',
          '--style-badge-border': '#e5e7eb',
          '--style-badge-text': '#374151',
          '--style-divider': '1px solid #e5e7eb',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Luxuriös, dunkel, premium',
        cssVars: {
          '--style-radius-sm': '0rem',
          '--style-radius-md': '0rem',
          '--style-radius-lg': '0rem',
          '--style-radius-full': '0rem',
          '--style-card-radius': '0rem',
          '--style-button-radius': '0rem',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.05em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 8px 32px rgba(0,0,0,0.3)',
          '--style-card-border': '1px solid rgba(212,175,55,0.3)',
          '--style-card-bg': '#1a1a2e',
          '--style-accent-glow': '0 0 20px rgba(212,175,55,0.3)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(10,10,20,0.95) 0%, rgba(10,10,20,0.7) 100%)',
          '--style-section-bg': '#0f0f1a',
          '--style-section-bg-alt': '#1a1a2e',
          '--style-text-primary': '#f5f0e8',
          '--style-text-secondary': '#a0a0b0',
          '--style-badge-bg': 'rgba(212,175,55,0.1)',
          '--style-badge-border': 'rgba(212,175,55,0.4)',
          '--style-badge-text': '#d4af37',
          '--style-divider': '1px solid rgba(212,175,55,0.2)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  cafe: {
    label: 'Café',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, einladend, gemütlich',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '4.5rem',
          '--style-card-shadow': '0 4px 16px rgba(92,64,51,0.08)',
          '--style-card-border': '1px solid rgba(92,64,51,0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(139,69,19,0.12)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(60,40,20,0.88) 0%, rgba(60,40,20,0.5) 60%, transparent 100%)',
          '--style-section-bg': '#fffdf9',
          '--style-section-bg-alt': '#faf5ef',
          '--style-text-primary': '#2c1810',
          '--style-text-secondary': '#6b5242',
          '--style-badge-bg': 'rgba(139,69,19,0.06)',
          '--style-badge-border': 'rgba(139,69,19,0.12)',
          '--style-badge-text': '#8b4513',
          '--style-divider': '1px solid rgba(92,64,51,0.1)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Hipster, urban, minimalistisch',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 2px 8px rgba(0,0,0,0.04)',
          '--style-card-border': '1px solid #e8e0d8',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(30,20,10,0.8) 0%, rgba(30,20,10,0.3) 100%)',
          '--style-section-bg': '#fdfcfa',
          '--style-section-bg-alt': '#f8f5f0',
          '--style-text-primary': '#1a1210',
          '--style-text-secondary': '#7a6a5a',
          '--style-badge-bg': '#f0ebe5',
          '--style-badge-border': '#e0d8cf',
          '--style-badge-text': '#4a3a2a',
          '--style-divider': '1px solid #e8e0d8',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Dunkel, industriell, Rösterei-Look',
        cssVars: {
          '--style-radius-sm': '0rem',
          '--style-radius-md': '0.25rem',
          '--style-radius-lg': '0.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.25rem',
          '--style-button-radius': '0rem',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.04em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 6px 24px rgba(0,0,0,0.25)',
          '--style-card-border': '1px solid rgba(180,120,60,0.3)',
          '--style-card-bg': '#2a1f15',
          '--style-accent-glow': '0 0 16px rgba(180,120,60,0.25)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(20,12,5,0.94) 0%, rgba(20,12,5,0.6) 100%)',
          '--style-section-bg': '#1a1008',
          '--style-section-bg-alt': '#2a1f15',
          '--style-text-primary': '#f5ede4',
          '--style-text-secondary': '#b8a898',
          '--style-badge-bg': 'rgba(180,120,60,0.12)',
          '--style-badge-border': 'rgba(180,120,60,0.35)',
          '--style-badge-text': '#d4a050',
          '--style-divider': '1px solid rgba(180,120,60,0.2)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  tattoo: {
    label: 'Tattoo',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Dunkel, edgy, Studio-Atmosphäre',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 20px rgba(0,0,0,0.3)',
          '--style-card-border': '1px solid rgba(255,255,255,0.08)',
          '--style-card-bg': '#1a1a1a',
          '--style-accent-glow': '0 0 20px rgba(220,38,38,0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.6) 100%)',
          '--style-section-bg': '#0a0a0a',
          '--style-section-bg-alt': '#111111',
          '--style-text-primary': '#f5f5f5',
          '--style-text-secondary': '#a3a3a3',
          '--style-text-muted': '#737373',
          '--style-badge-bg': 'rgba(220,38,38,0.08)',
          '--style-badge-border': 'rgba(220,38,38,0.2)',
          '--style-badge-text': '#ef4444',
          '--style-divider': '1px solid rgba(255,255,255,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, clean, Galerie-Stil',
        cssVars: {
          '--style-radius-sm': '0rem',
          '--style-radius-md': '0.25rem',
          '--style-radius-lg': '0.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.25rem',
          '--style-button-radius': '0rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid rgba(255,255,255,0.06)',
          '--style-card-bg': '#171717',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.4) 100%)',
          '--style-section-bg': '#0d0d0d',
          '--style-section-bg-alt': '#141414',
          '--style-text-primary': '#e5e5e5',
          '--style-text-secondary': '#737373',
          '--style-text-muted': '#525252',
          '--style-badge-border': 'rgba(255,255,255,0.1)',
          '--style-badge-text': '#d4d4d4',
          '--style-divider': '1px solid rgba(255,255,255,0.06)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Neon, laut, Streetstyle',
        cssVars: {
          '--style-radius-sm': '0rem',
          '--style-radius-md': '0rem',
          '--style-radius-lg': '0.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0rem',
          '--style-button-radius': '0rem',
          '--style-heading-weight': '900',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.05em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 0 24px rgba(220,38,38,0.2)',
          '--style-card-border': '2px solid rgba(220,38,38,0.3)',
          '--style-card-bg': '#0f0f0f',
          '--style-accent-glow': '0 0 30px rgba(220,38,38,0.3)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.95) 0%, rgba(30,0,0,0.7) 100%)',
          '--style-section-bg': '#050505',
          '--style-section-bg-alt': '#0f0f0f',
          '--style-text-primary': '#ffffff',
          '--style-text-secondary': '#a3a3a3',
          '--style-text-muted': '#737373',
          '--style-badge-bg': 'rgba(220,38,38,0.15)',
          '--style-badge-border': 'rgba(220,38,38,0.4)',
          '--style-badge-text': '#f87171',
          '--style-divider': '2px solid rgba(220,38,38,0.2)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  consulting: {
    label: 'Kanzlei & Beratung',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Seriös, vertrauenswürdig, professionell',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 16px rgba(15,23,42,0.06)',
          '--style-card-border': '1px solid rgba(15,23,42,0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(30,58,138,0.1)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,23,42,0.9) 0%, rgba(30,58,138,0.7) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#64748b',
          '--style-badge-bg': 'rgba(30,58,138,0.05)',
          '--style-badge-border': 'rgba(30,58,138,0.12)',
          '--style-badge-text': '#1e3a8a',
          '--style-divider': '1px solid rgba(15,23,42,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Clean, zeitgemäß, tech-affin',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 2px 8px rgba(0,0,0,0.04)',
          '--style-card-border': '1px solid #e2e8f0',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(15,23,42,0.85) 0%, rgba(15,23,42,0.4) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f1f5f9',
          '--style-text-primary': '#1e293b',
          '--style-text-secondary': '#64748b',
          '--style-badge-bg': '#f1f5f9',
          '--style-badge-border': '#e2e8f0',
          '--style-badge-text': '#334155',
          '--style-divider': '1px solid #e2e8f0',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Dunkel, prägnant, Autorität',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '4.5rem',
          '--style-card-shadow': '0 8px 32px rgba(0,0,0,0.2)',
          '--style-card-border': '1px solid rgba(255,255,255,0.06)',
          '--style-card-bg': '#1e293b',
          '--style-accent-glow': '0 0 20px rgba(59,130,246,0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(2,6,23,0.95) 0%, rgba(15,23,42,0.8) 100%)',
          '--style-section-bg': '#0f172a',
          '--style-section-bg-alt': '#1e293b',
          '--style-text-primary': '#f1f5f9',
          '--style-text-secondary': '#94a3b8',
          '--style-badge-bg': 'rgba(59,130,246,0.1)',
          '--style-badge-border': 'rgba(59,130,246,0.25)',
          '--style-badge-text': '#60a5fa',
          '--style-divider': '1px solid rgba(255,255,255,0.06)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  ecommerce: {
    label: 'E-Commerce',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Vertrauenswürdig, sauber, shopfreundlich',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 2px 8px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid #e5e7eb',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.1) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f9fafb',
          '--style-text-primary': '#111827',
          '--style-text-secondary': '#4b5563',
          '--style-text-muted': '#9ca3af',
          '--style-badge-bg': 'rgba(79,70,229,0.06)',
          '--style-badge-border': 'rgba(79,70,229,0.15)',
          '--style-badge-text': '#4f46e5',
          '--style-divider': '1px solid #e5e7eb',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, großzügig, Lifestyle-Shop',
        cssVars: {
          '--style-radius-sm': '0rem',
          '--style-radius-md': '0.25rem',
          '--style-radius-lg': '0.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.25rem',
          '--style-button-radius': '0rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.05em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': 'none',
          '--style-card-border': '1px solid #e5e7eb',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.5) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#fafafa',
          '--style-text-primary': '#0a0a0a',
          '--style-text-secondary': '#525252',
          '--style-text-muted': '#a3a3a3',
          '--style-badge-bg': 'rgba(0,0,0,0.04)',
          '--style-badge-border': 'rgba(0,0,0,0.08)',
          '--style-badge-text': '#171717',
          '--style-divider': '1px solid #e5e7eb',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Kräftig, auffällig, Sale-orientiert',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 8px 24px rgba(0,0,0,0.08)',
          '--style-card-border': 'none',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(99,102,241,0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(79,70,229,0.85) 0%, rgba(236,72,153,0.7) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f5f3ff',
          '--style-text-primary': '#1e1b4b',
          '--style-text-secondary': '#4338ca',
          '--style-text-muted': '#818cf8',
          '--style-badge-bg': 'rgba(99,102,241,0.1)',
          '--style-badge-border': 'rgba(99,102,241,0.2)',
          '--style-badge-text': '#6366f1',
          '--style-divider': '1px solid rgba(99,102,241,0.1)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  retail: {
    label: 'Einzelhandel & Weitere',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, einladend, vertrauensvoll',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.015em',
          '--style-section-spacing': '4.5rem',
          '--style-card-shadow': '0 2px 12px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(var(--brand-primary-rgb, 16 185 129), 0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,23,42,0.85) 0%, rgba(15,23,42,0.6) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#475569',
          '--style-text-muted': '#94a3b8',
          '--style-badge-bg': 'rgba(16,185,129,0.08)',
          '--style-badge-border': 'rgba(16,185,129,0.2)',
          '--style-badge-text': '#059669',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
      modern: {
        label: 'Modern',
        description: 'Minimalistisch, clean, luftig',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '600',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 1px 3px rgba(0,0,0,0.04)',
          '--style-card-border': '1px solid rgba(0,0,0,0.05)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(180deg, rgba(15,23,42,0.7) 0%, rgba(15,23,42,0.4) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#fafafa',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#475569',
          '--style-text-muted': '#94a3b8',
          '--style-badge-bg': 'rgba(15,23,42,0.04)',
          '--style-badge-border': 'rgba(15,23,42,0.08)',
          '--style-badge-text': '#334155',
          '--style-divider': '1px solid rgba(0,0,0,0.05)',
          '--style-heading-font': 'var(--font-inter)',
        },
      },
      bold: {
        label: 'Bold',
        description: 'Kräftig, auffällig, Sale-orientiert',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '800',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.02em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 8px 30px rgba(0,0,0,0.1)',
          '--style-card-border': 'none',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 25px rgba(239,68,68,0.2)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(127,29,29,0.9) 0%, rgba(239,68,68,0.7) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#fafafa',
          '--style-text-primary': '#1c1917',
          '--style-text-secondary': '#57534e',
          '--style-text-muted': '#a8a29e',
          '--style-badge-bg': 'rgba(239,68,68,0.1)',
          '--style-badge-border': 'rgba(239,68,68,0.25)',
          '--style-badge-text': '#dc2626',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
};

export function getStyleConfig(industry: string, style: string): StyleConfig | null {
  return INDUSTRY_STYLES[industry]?.styles[style] ?? INDUSTRY_STYLES[industry]?.styles['classic'] ?? null;
}

export function getStyleCssVars(industry: string, style: string): Record<string, string> {
  return getStyleConfig(industry, style)?.cssVars ?? {};
}
