/**
 * Style definitions for each industry.
 * Flamingo uses a single classic site style. Visual variation comes from
 * global brand tokens and section-level color overrides.
 */

export type StyleConfig = {
  label: string;
  description: string;
  cssVars: Record<string, string>;
};

export type IndustryStyles = {
  label: string;
  styles: Record<string, StyleConfig>;
};

export const INDUSTRY_STYLES: Record<string, IndustryStyles> = {
  tradesman: {
    label: 'Handwerk',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Vertrauenswürdig, professionell, bewährt',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 20px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': 'rgba(255,255,255,1)',
          '--style-accent-glow': '0 0 30px rgba(243, 156, 18, 0.2)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(13,33,55,0.9) 0%, rgba(13,33,55,0.7) 50%, rgba(13,33,55,0.5) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#64748b',
          '--style-badge-bg': 'rgba(26, 82, 118, 0.05)',
          '--style-badge-border': 'rgba(26, 82, 118, 0.1)',
          '--style-divider': '1px solid rgba(0,0,0,0.06)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  restaurant: {
    label: 'Restaurant',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, hochwertig, einladend',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.875rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 50px rgba(57, 34, 18, 0.10)',
          '--style-card-border': '1px solid rgba(57, 34, 18, 0.10)',
          '--style-card-bg': '#fffaf2',
          '--style-accent-glow': '0 0 36px rgba(183, 99, 47, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(30,18,12,0.92) 0%, rgba(68,37,22,0.72) 58%, rgba(30,18,12,0.45) 100%)',
          '--style-section-bg': '#fffaf2',
          '--style-section-bg-alt': '#f4eadc',
          '--style-text-primary': '#28160f',
          '--style-text-secondary': '#806957',
          '--style-text-muted': '#806957',
          '--style-accent': '#b7632f',
          '--style-brand': '#7e4023',
          '--style-badge-bg': 'rgba(126, 64, 35, 0.10)',
          '--style-badge-border': 'rgba(126, 64, 35, 0.16)',
          '--style-badge-text': '#7e4023',
          '--style-divider': '1px solid rgba(57,34,18,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  hotel: {
    label: 'Hotel',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Boutique, ruhig, hochwertig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 60px rgba(15, 30, 50, 0.08)',
          '--style-card-border': '1px solid rgba(15, 30, 50, 0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 36px rgba(26, 58, 92, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(12,24,42,0.93) 0%, rgba(25,48,72,0.72) 55%, rgba(12,24,42,0.44) 100%)',
          '--style-section-bg': '#f7f8fb',
          '--style-section-bg-alt': '#eef0f5',
          '--style-text-primary': '#0f1d2e',
          '--style-text-secondary': '#4b5c72',
          '--style-text-muted': '#6b7a8d',
          '--style-accent': '#1a3a5c',
          '--style-brand': '#1a3550',
          '--style-badge-bg': '#1a3a5c',
          '--style-badge-border': '#15304e',
          '--style-badge-text': '#ffffff',
          '--style-divider': '1px solid rgba(15,30,50,0.10)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  tourism: {
    label: 'Tourismus',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Regional, naturnah, einladend',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.875rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(31, 73, 54, 0.10)',
          '--style-card-border': '1px solid rgba(31, 73, 54, 0.10)',
          '--style-card-bg': '#fbfaf1',
          '--style-accent-glow': '0 0 36px rgba(76, 133, 87, 0.22)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(19,48,38,0.92) 0%, rgba(45,91,67,0.68) 56%, rgba(19,48,38,0.40) 100%)',
          '--style-section-bg': '#fbfaf1',
          '--style-section-bg-alt': '#e9f0df',
          '--style-text-primary': '#183226',
          '--style-text-secondary': '#667765',
          '--style-badge-bg': '#d7e8b8',
          '--style-badge-border': '#d7e8b8',
          '--style-badge-text': '#3f642f',
          '--style-divider': '1px solid rgba(31,73,54,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  salon: {
    label: 'Salon',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Weich, hochwertig, Beauty-orientiert',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(98, 46, 74, 0.10)',
          '--style-card-border': '1px solid rgba(98, 46, 74, 0.10)',
          '--style-card-bg': '#fff7fb',
          '--style-accent-glow': '0 0 36px rgba(194, 82, 138, 0.20)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(54,24,43,0.92) 0%, rgba(105,55,78,0.68) 56%, rgba(54,24,43,0.40) 100%)',
          '--style-section-bg': '#fff7fb',
          '--style-section-bg-alt': '#f7e8ef',
          '--style-text-primary': '#321827',
          '--style-text-secondary': '#7b6472',
          '--style-text-muted': '#7b6472',
          '--style-accent': '#c2528a',
          '--style-brand': '#7a2c55',
          '--style-badge-bg': '#f3c7dc',
          '--style-badge-border': '#f3c7dc',
          '--style-badge-text': '#7a2c55',
          '--style-divider': '1px solid rgba(98,46,74,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  wedding: {
    label: 'Hochzeit',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Romantisch, elegant, zeitlos',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '2rem',
          '--style-heading-weight': '300',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0.02em',
          '--style-section-spacing': '6rem',
          '--style-card-shadow': '0 12px 40px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 40px rgba(180,140,120,0.15)',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(20,15,10,0.4) 0%, rgba(20,15,10,0.2) 50%, rgba(20,15,10,0.5) 100%)',
          '--style-section-bg': '#fffcfa',
          '--style-section-bg-alt': '#f9f5f2',
          '--style-text-primary': '#2c2420',
          '--style-text-secondary': '#7a6b60',
          '--style-badge-bg': 'rgba(180,140,120,0.08)',
          '--style-badge-border': 'rgba(180,140,120,0.15)',
          '--style-badge-text': '#8b6f5c',
          '--style-divider': '1px solid rgba(180,140,120,0.15)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  photography: {
    label: 'Fotografie',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Elegant, galerie-inspiriert, bildlastig',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '2rem',
          '--style-heading-weight': '300',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '6rem',
          '--style-card-shadow': '0 12px 40px rgba(0,0,0,0.08)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 30px rgba(0,0,0,0.08)',
          '--style-hero-overlay': 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.1) 50%, rgba(0,0,0,0.4) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f7f7f5',
          '--style-text-primary': '#1a1a1a',
          '--style-text-secondary': '#6b6b6b',
          '--style-badge-bg': 'rgba(0,0,0,0.04)',
          '--style-badge-border': 'rgba(0,0,0,0.08)',
          '--style-badge-text': '#1a1a1a',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  medical: {
    label: 'Aerzte & Praxen',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Serioes, ruhig, vertrauenswuerdig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '0',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 18px 55px rgba(15, 76, 92, 0.10)',
          '--style-card-border': '1px solid rgba(15, 76, 92, 0.10)',
          '--style-card-bg': '#f7fcfb',
          '--style-accent-glow': '0 0 36px rgba(82, 168, 176, 0.20)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(8,47,61,0.92) 0%, rgba(15,76,92,0.68) 56%, rgba(8,47,61,0.40) 100%)',
          '--style-section-bg': '#f7fcfb',
          '--style-section-bg-alt': '#e6f3f1',
          '--style-text-primary': '#0f2f3a',
          '--style-text-secondary': '#63777a',
          '--style-badge-bg': '#d5eeeb',
          '--style-badge-border': '#d5eeeb',
          '--style-badge-text': '#0f4c5c',
          '--style-divider': '1px solid rgba(15,76,92,0.12)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  realestate: {
    label: 'Immobilien',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Seriös, vertrauensvoll, hochwertig',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 24px rgba(0,0,0,0.08)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 24px rgba(30, 64, 110, 0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,30,55,0.92) 0%, rgba(15,30,55,0.6) 60%, transparent 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f4f7fa',
          '--style-text-primary': '#1a2536',
          '--style-text-secondary': '#5a6a7a',
          '--style-badge-bg': 'rgba(30, 64, 110, 0.06)',
          '--style-badge-border': 'rgba(30, 64, 110, 0.12)',
          '--style-badge-text': '#1e406e',
          '--style-divider': '1px solid rgba(0,0,0,0.06)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  cafe: {
    label: 'Café',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, einladend, gemütlich',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '1rem',
          '--style-radius-lg': '1.5rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '1rem',
          '--style-button-radius': '0.75rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '4.5rem',
          '--style-card-shadow': '0 4px 16px rgba(92,64,51,0.08)',
          '--style-card-border': '1px solid rgba(92,64,51,0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(139,69,19,0.12)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(60,40,20,0.88) 0%, rgba(60,40,20,0.5) 60%, transparent 100%)',
          '--style-section-bg': '#fffdf9',
          '--style-section-bg-alt': '#faf5ef',
          '--style-text-primary': '#2c1810',
          '--style-text-secondary': '#6b5242',
          '--style-badge-bg': 'rgba(139,69,19,0.06)',
          '--style-badge-border': 'rgba(139,69,19,0.12)',
          '--style-badge-text': '#8b4513',
          '--style-divider': '1px solid rgba(92,64,51,0.1)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  tattoo: {
    label: 'Tattoo',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Dunkel, edgy, Studio-Atmosphäre',
        cssVars: {
          '--style-radius-sm': '0.25rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.5rem',
          '--style-button-radius': '0.25rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'uppercase',
          '--style-heading-tracking': '0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 20px rgba(0,0,0,0.3)',
          '--style-card-border': '1px solid rgba(255,255,255,0.08)',
          '--style-card-bg': '#1a1a1a',
          '--style-accent-glow': '0 0 20px rgba(220,38,38,0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.6) 100%)',
          '--style-section-bg': '#0a0a0a',
          '--style-section-bg-alt': '#111111',
          '--style-text-primary': '#f5f5f5',
          '--style-text-secondary': '#a3a3a3',
          '--style-text-muted': '#737373',
          '--style-badge-bg': 'rgba(220,38,38,0.08)',
          '--style-badge-border': 'rgba(220,38,38,0.2)',
          '--style-badge-text': '#ef4444',
          '--style-divider': '1px solid rgba(255,255,255,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  consulting: {
    label: 'Kanzlei & Beratung',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Seriös, vertrauenswürdig, professionell',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.02em',
          '--style-section-spacing': '5rem',
          '--style-card-shadow': '0 4px 16px rgba(15,23,42,0.06)',
          '--style-card-border': '1px solid rgba(15,23,42,0.08)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(30,58,138,0.1)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,23,42,0.9) 0%, rgba(30,58,138,0.7) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#64748b',
          '--style-badge-bg': 'rgba(30,58,138,0.05)',
          '--style-badge-border': 'rgba(30,58,138,0.12)',
          '--style-badge-text': '#1e3a8a',
          '--style-divider': '1px solid rgba(15,23,42,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  ecommerce: {
    label: 'E-Commerce',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Vertrauenswürdig, sauber, shopfreundlich',
        cssVars: {
          '--style-radius-sm': '0.375rem',
          '--style-radius-md': '0.5rem',
          '--style-radius-lg': '0.75rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.01em',
          '--style-section-spacing': '4rem',
          '--style-card-shadow': '0 2px 8px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid #e5e7eb',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': 'none',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.1) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f9fafb',
          '--style-text-primary': '#111827',
          '--style-text-secondary': '#4b5563',
          '--style-text-muted': '#9ca3af',
          '--style-badge-bg': 'rgba(79,70,229,0.06)',
          '--style-badge-border': 'rgba(79,70,229,0.15)',
          '--style-badge-text': '#4f46e5',
          '--style-divider': '1px solid #e5e7eb',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
  retail: {
    label: 'Einzelhandel & Weitere',
    styles: {
      classic: {
        label: 'Klassisch',
        description: 'Warm, einladend, vertrauensvoll',
        cssVars: {
          '--style-radius-sm': '0.5rem',
          '--style-radius-md': '0.75rem',
          '--style-radius-lg': '1.25rem',
          '--style-radius-full': '2rem',
          '--style-card-radius': '0.75rem',
          '--style-button-radius': '0.5rem',
          '--style-heading-weight': '700',
          '--style-heading-transform': 'none',
          '--style-heading-tracking': '-0.015em',
          '--style-section-spacing': '4.5rem',
          '--style-card-shadow': '0 2px 12px rgba(0,0,0,0.06)',
          '--style-card-border': '1px solid rgba(0,0,0,0.06)',
          '--style-card-bg': '#ffffff',
          '--style-accent-glow': '0 0 20px rgba(var(--brand-primary-rgb, 16 185 129), 0.15)',
          '--style-hero-overlay': 'linear-gradient(135deg, rgba(15,23,42,0.85) 0%, rgba(15,23,42,0.6) 100%)',
          '--style-section-bg': '#ffffff',
          '--style-section-bg-alt': '#f8fafc',
          '--style-text-primary': '#0f172a',
          '--style-text-secondary': '#475569',
          '--style-text-muted': '#94a3b8',
          '--style-badge-bg': 'rgba(16,185,129,0.08)',
          '--style-badge-border': 'rgba(16,185,129,0.2)',
          '--style-badge-text': '#059669',
          '--style-divider': '1px solid rgba(0,0,0,0.08)',
          '--style-heading-font': 'var(--font-outfit)',
        },
      },
    },
  },
};

INDUSTRY_STYLES.florist = {
  label: 'Floristik',
  styles: INDUSTRY_STYLES.salon.styles,
};

INDUSTRY_STYLES.fitness = {
  label: 'Fitnessstudio',
  styles: INDUSTRY_STYLES.tradesman.styles,
};

INDUSTRY_STYLES.location = {
  label: 'Location',
  styles: INDUSTRY_STYLES.hotel.styles,
};

export function getStyleConfig(industry: string, style: string): StyleConfig | null {
  return INDUSTRY_STYLES[industry]?.styles['classic'] ?? INDUSTRY_STYLES[industry]?.styles[style] ?? null;
}

export function getStyleCssVars(industry: string, style: string): Record<string, string> {
  return getStyleConfig(industry, style)?.cssVars ?? {};
}
