import type { SectionProps } from './restaurant';
import { HeroSection } from './handwerk/hero';
import { UspStripSection } from './handwerk/usp-strip';
import { ServicesGridSection } from './handwerk/services-grid';
import { ProcessStepsSection } from './handwerk/process-steps';
import { TestimonialsSection } from './handwerk/testimonials';
import { FaqSection } from './handwerk/faq';
import { CtaBandSection } from './handwerk/cta-band';
import { ContactSection } from './handwerk/contact';
import { MapSection } from './handwerk/map';
import { ServiceDetailSection } from './handwerk/service-detail';
import { PortfolioSection } from './handwerk/portfolio';
import { TeamSection } from './handwerk/team';
import { CtaLinksSection } from './handwerk/cta-links';
import { NewsPreviewSection } from './handwerk/news-preview';
import { StatsSection } from './handwerk/stats';
import { LogoCloudSection } from './handwerk/logo-cloud';
import { GalleryGridSection } from './handwerk/gallery-grid';
import { RichTextSection } from './handwerk/rich-text';
import { HeaderBannerSection } from './handwerk/header-banner';
import { CollectionHeroSection } from './handwerk/collection-hero';
import { TextImageSection } from './handwerk/text-image';
import {
  PortfolioGallerySection,
  ServicePackagesSection,
  PhotographerAboutSection,
  ShootingProcessSection,
} from './photography';
import {
  AmbienceSection,
  EventsSection,
  MenuSection,
  OpeningHoursSection,
  RestaurantContactSection,
  RestaurantFaqSection,
  RestaurantGallerySection,
  RestaurantHeroSection,
  RestaurantStorySection,
  RestaurantTestimonialsSection,
  ReservationSection,
  SignatureDishesSection,
} from './restaurant';
import {
  AmenitiesSection,
  BookingStripSection,
  EventSpacesSection,
  HotelContactSection,
  HotelDiningSection,
  HotelFaqSection,
  HotelGallerySection,
  HotelHeroSection,
  HotelTestimonialsSection,
  LocationSection,
  OffersSection,
  RoomShowcaseSection,
  HotelStorySection,
  WellnessSection,
} from './hotel';
import {
  AccommodationGridSection,
  DestinationHighlightsSection,
  DownloadGuidesSection,
  EventsCalendarSection,
  ExperienceGridSection,
  PlacesMapSection,
  SeasonTeaserSection,
  SightseeingListSection,
  TourismContactSection,
  TourismFaqSection,
  TourismGallerySection,
  TourismHeroSection,
  TourismStorySection,
  TourismTestimonialsSection,
  TourRoutesSection,
  VisitorInfoSection,
} from './tourism';
import {
  BeforeAfterSection,
  BookingCtaSection,
  ExpertiseGridSection,
  LocationContactSection,
  PackagesSection,
  PriceListSection,
  SalonFaqSection,
  SalonGallerySection,
  SalonHeroSection,
  SalonOpeningHoursSection,
  SalonTestimonialsSection,
  ServiceMenuSection,
  TeamShowcaseSection,
  TreatmentDetailSection,
} from './salon';
import {
  WeddingHeroSection,
  CoupleStorySection,
  EventScheduleSection,
  VenueInfoSection,
  TravelInfoSection,
  WeddingPartySection,
  GiftRegistrySection,
  DresscodeSection,
  RsvpSection,
  WeddingMenuSection,
  WeddingFaqSection,
  WeddingGallerySection,
} from './wedding';
import {
  AppointmentCtaSection,
  CertificationsSection,
  DiagnosticsSection,
  DoctorTeamSection,
  DownloadFormsSection,
  EmergencyInfoSection,
  EquipmentHighlightsSection,
  InsuranceInfoSection,
  MedicalFaqSection,
  MedicalHeroSection,
  MedicalLocationContactSection,
  MedicalOpeningHoursSection,
  PatientInfoSection,
  PracticeGallerySection,
  PracticeTeamSection,
  ServiceOverviewSection,
  TreatmentDetailSection as MedicalTreatmentDetailSection,
  MedicalStorySection,
  MedicalTestimonialsSection,
  ValuesGridSection,
} from './medical';

export type TemplateComponent = React.FC<SectionProps>;

export const TRADESMAN_TEMPLATES: Record<string, TemplateComponent> = {
  hero: HeroSection,
  uspStrip: UspStripSection,
  servicesGrid: ServicesGridSection,
  processSteps: ProcessStepsSection,
  testimonials: TestimonialsSection,
  faq: FaqSection,
  ctaBand: CtaBandSection,
  contact: ContactSection,
  map: MapSection,
  serviceDetail: ServiceDetailSection,
  portfolio: PortfolioSection,
  team: TeamSection,
  ctaLinks: CtaLinksSection,
  newsPreview: NewsPreviewSection,
  newsGrid: NewsPreviewSection,
  stats: StatsSection,
  logoCloud: LogoCloudSection,
  galleryGrid: GalleryGridSection,
  richText: RichTextSection,
  headerBanner: HeaderBannerSection,
  textImage: TextImageSection,
  collectionHero: CollectionHeroSection,
};

export const RESTAURANT_TEMPLATES: Record<string, TemplateComponent> = {
  hero: RestaurantHeroSection,
  menu: MenuSection,
  reservation: ReservationSection,
  openingHours: OpeningHoursSection,
  signatureDishes: SignatureDishesSection,
  events: EventsSection,
  ambience: AmbienceSection,
  contact: RestaurantContactSection,
  gallery: RestaurantGallerySection,
  faq: RestaurantFaqSection,
  story: RestaurantStorySection,
  testimonials: RestaurantTestimonialsSection,
  newsPreview: NewsPreviewSection,
  newsGrid: NewsPreviewSection,
  uspStrip: UspStripSection,
  ctaBand: CtaBandSection,
  textImage: TextImageSection,
  richText: RichTextSection,
  collectionHero: CollectionHeroSection,
};

export const INDUSTRY_TEMPLATES: Record<string, Record<string, TemplateComponent>> = {
  tradesman: TRADESMAN_TEMPLATES,
  restaurant: RESTAURANT_TEMPLATES,
  hotel: {
    hero: HotelHeroSection,
    bookingStrip: BookingStripSection,
    roomShowcase: RoomShowcaseSection,
    offers: OffersSection,
    amenities: AmenitiesSection,
    wellness: WellnessSection,
    location: LocationSection,
    hotelDining: HotelDiningSection,
    eventSpaces: EventSpacesSection,
    gallery: HotelGallerySection,
    testimonials: HotelTestimonialsSection,
    faq: HotelFaqSection,
    contact: HotelContactSection,
    story: HotelStorySection,
    newsPreview: NewsPreviewSection,
    newsGrid: NewsPreviewSection,
    uspStrip: UspStripSection,
    ctaBand: CtaBandSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    collectionHero: CollectionHeroSection,
  },
  tourism: {
    hero: TourismHeroSection,
    destinationHighlights: DestinationHighlightsSection,
    experienceGrid: ExperienceGridSection,
    seasonTeaser: SeasonTeaserSection,
    eventsCalendar: EventsCalendarSection,
    placesMap: PlacesMapSection,
    sightseeingList: SightseeingListSection,
    tourRoutes: TourRoutesSection,
    accommodationGrid: AccommodationGridSection,
    visitorInfo: VisitorInfoSection,
    downloadGuides: DownloadGuidesSection,
    gallery: TourismGallerySection,
    faq: TourismFaqSection,
    tourismContact: TourismContactSection,
    testimonials: TourismTestimonialsSection,
    story: TourismStorySection,
    newsPreview: NewsPreviewSection,
    newsGrid: NewsPreviewSection,
    uspStrip: UspStripSection,
    ctaBand: CtaBandSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    collectionHero: CollectionHeroSection,
  },
  salon: {
    hero: SalonHeroSection,
    serviceMenu: ServiceMenuSection,
    priceList: PriceListSection,
    treatmentDetail: TreatmentDetailSection,
    packages: PackagesSection,
    teamShowcase: TeamShowcaseSection,
    expertiseGrid: ExpertiseGridSection,
    beforeAfter: BeforeAfterSection,
    gallery: SalonGallerySection,
    testimonials: SalonTestimonialsSection,
    openingHours: SalonOpeningHoursSection,
    bookingCta: BookingCtaSection,
    locationContact: LocationContactSection,
    faq: SalonFaqSection,
    newsPreview: NewsPreviewSection,
    newsGrid: NewsPreviewSection,
    uspStrip: UspStripSection,
    ctaBand: CtaBandSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    collectionHero: CollectionHeroSection,
  },
  medical: {
    hero: MedicalHeroSection,
    serviceOverview: ServiceOverviewSection,
    treatmentDetail: MedicalTreatmentDetailSection,
    diagnostics: DiagnosticsSection,
    doctorTeam: DoctorTeamSection,
    practiceTeam: PracticeTeamSection,
    certifications: CertificationsSection,
    patientInfo: PatientInfoSection,
    insuranceInfo: InsuranceInfoSection,
    downloadForms: DownloadFormsSection,
    appointmentCta: AppointmentCtaSection,
    openingHours: MedicalOpeningHoursSection,
    emergencyInfo: EmergencyInfoSection,
    practiceGallery: PracticeGallerySection,
    equipmentHighlights: EquipmentHighlightsSection,
    valuesGrid: ValuesGridSection,
    locationContact: MedicalLocationContactSection,
    faq: MedicalFaqSection,
    testimonials: MedicalTestimonialsSection,
    story: MedicalStorySection,
    newsPreview: NewsPreviewSection,
    newsGrid: NewsPreviewSection,
    uspStrip: UspStripSection,
    ctaBand: CtaBandSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    collectionHero: CollectionHeroSection,
  },
  wedding: {
    hero: WeddingHeroSection,
    coupleStory: CoupleStorySection,
    eventSchedule: EventScheduleSection,
    venueInfo: VenueInfoSection,
    travelInfo: TravelInfoSection,
    weddingParty: WeddingPartySection,
    giftRegistry: GiftRegistrySection,
    dresscode: DresscodeSection,
    rsvp: RsvpSection,
    weddingMenu: WeddingMenuSection,
    faq: WeddingFaqSection,
    gallery: WeddingGallerySection,
    uspStrip: UspStripSection,
    ctaBand: CtaBandSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    collectionHero: CollectionHeroSection,
  },
  photography: {
    hero: HeroSection,
    portfolioGallery: PortfolioGallerySection,
    servicesGrid: ServicesGridSection,
    servicePackages: ServicePackagesSection,
    photographerAbout: PhotographerAboutSection,
    shootingProcess: ShootingProcessSection,
    testimonials: TestimonialsSection,
    faq: FaqSection,
    contact: ContactSection,
    map: MapSection,
    ctaBand: CtaBandSection,
    uspStrip: UspStripSection,
    textImage: TextImageSection,
    richText: RichTextSection,
    newsPreview: NewsPreviewSection,
    newsGrid: NewsPreviewSection,
    collectionHero: CollectionHeroSection,
  },
};

// Shared/generic sections available to ALL templates
const SHARED_TEMPLATES: Record<string, TemplateComponent> = {
  uspStrip: UspStripSection,
  servicesGrid: ServicesGridSection,
  processSteps: ProcessStepsSection,
  ctaBand: CtaBandSection,
  ctaLinks: CtaLinksSection,
  newsPreview: NewsPreviewSection,
  newsGrid: NewsPreviewSection,
  stats: StatsSection,
  logoCloud: LogoCloudSection,
  galleryGrid: GalleryGridSection,
  richText: RichTextSection,
  headerBanner: HeaderBannerSection,
  textImage: TextImageSection,
  collectionHero: CollectionHeroSection,
  contact: ContactSection,
  map: MapSection,
  testimonials: TestimonialsSection,
  faq: FaqSection,
  team: TeamSection,
  portfolio: PortfolioSection,
  serviceDetail: ServiceDetailSection,
  portfolioGallery: PortfolioGallerySection,
  servicePackages: ServicePackagesSection,
  photographerAbout: PhotographerAboutSection,
  shootingProcess: ShootingProcessSection,
};

export function getIndustryTemplates(industry: string): Record<string, TemplateComponent> {
  const specific = INDUSTRY_TEMPLATES[industry] ?? TRADESMAN_TEMPLATES;
  return { ...SHARED_TEMPLATES, ...specific };
}
