import type { DemoSite } from './types';
import { B, HERO } from './types';

export const restaurantSite: DemoSite = {
  industry: 'restaurant',
  industryKey: 'restaurant',
  defaultStyle: 'classic',
  pages: [
    {
      slug: '',
      title: 'Startseite',
      sections: [
        {
          ...HERO,
          id: 'rs-home-hero',
          type: 'hero',
          data: {
            headline: 'Trattoria Dal Maestro',
            subline: 'Authentische italienische Kueche seit 1998 — mitten in der Innsbrucker Altstadt',
            badgeText: 'Seit 1998',
            bgImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1800&q=85',
            trustItems: ['Authentische italienische Kueche', 'Seit 25 Jahren', 'Familiengefuehrt'],
            primaryCta: { label: 'Tisch reservieren', href: '/demo/restaurant/reservierung' },
            secondaryCta: { label: 'Speisekarte entdecken', href: '/demo/restaurant/speisekarte' },
          },
        },
        {
          ...B,
          id: 'rs-home-dishes',
          type: 'signatureDishes',
          data: {
            headline: 'Unsere Signature-Gerichte',
            subline: 'Drei Klassiker, die unsere Gaeste immer wieder zurueckbringen',
            dishes: [
              {
                name: 'Osso Buco alla Milanese',
                description: 'Geschmorte Kalbshaxe nach Mailaender Art, serviert auf safrangelben Risotto mit Gremolata — unser meistbestelltes Gericht seit der Eroeffnung.',
                price: '34,00 €',
                image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=80',
                imageAlt: 'Osso Buco mit Risotto auf weissem Teller',
                label: "Chef's Pick",
                ingredients: ['Kalbshaxe', 'Safranrisotto', 'Gremolata', 'Weisswein', 'Rosmarin'],
                cta: { label: 'Zur Speisekarte', href: '/demo/restaurant/speisekarte' },
              },
              {
                name: 'Tagliatelle al Tartufo',
                description: 'Frische, handgerollte Tagliatelle mit schwarzem Trueffel aus Norcia, Parmigiano Reggiano 36 Monate und einem Hauch Trueffeloel.',
                price: '24,00 €',
                image: 'https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=900&q=80',
                imageAlt: 'Frische Tagliatelle mit Trueffel-Shavings',
                label: 'Saisonhighlight',
                ingredients: ['Frische Tagliatelle', 'Schwarzer Trueffel', 'Parmigiano Reggiano', 'Butter', 'Trueffeloel'],
                cta: { label: 'Zur Speisekarte', href: '/demo/restaurant/speisekarte' },
              },
              {
                name: 'Tiramisù della Casa',
                description: 'Unser legendaeres Hausdessert nach dem Originalrezept von Nonna Maria — mit Mascarpone, Espresso und Amaretto, 24 Stunden durchgezogen.',
                price: '12,00 €',
                image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&q=80',
                imageAlt: 'Klassisches Tiramisù im Glas mit Kakaopulver',
                label: 'Dolce Vita',
                ingredients: ['Mascarpone', 'Espresso', 'Loeffelbiskuit', 'Amaretto', 'Kakao'],
                cta: { label: 'Alle Dolci', href: '/demo/restaurant/speisekarte' },
              },
            ],
          },
        },
        {
          ...B,
          id: 'rs-home-reservation',
          type: 'reservation',
          data: {
            headline: 'Reservieren Sie Ihren Tisch',
            subline: 'Geniessen Sie einen unvergesslichen Abend in der Trattoria Dal Maestro',
            introText: 'Ob romantisches Dinner zu zweit oder gesellige Runde mit Freunden — wir freuen uns auf Ihren Besuch. Reservieren Sie bequem online oder rufen Sie uns an.',
            externalBookingCta: { label: 'Jetzt reservieren', href: '/demo/restaurant/reservierung' },
            phoneCta: { label: '+43 512 123 456', href: 'tel:+43512123456' },
            timeHint: 'Wir empfehlen eine Reservierung mindestens 2 Tage im Voraus, besonders fuer Freitag und Samstag.',
          },
        },
      ],
    },
    {
      slug: 'speisekarte',
      title: 'Speisekarte',
      sections: [
        {
          ...HERO,
          id: 'rs-menu-hero',
          type: 'hero',
          data: {
            headline: 'Unsere Speisekarte',
            subline: 'Frische Zutaten, traditionelle Rezepte, leidenschaftlich zubereitet',
            bgImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1800&q=85',
            primaryCta: { label: 'Tisch reservieren', href: '/demo/restaurant/reservierung' },
          },
        },
        {
          ...B,
          id: 'rs-menu-full',
          type: 'menu',
          data: {
            headline: 'La Carta',
            footnote: 'Alle Gerichte werden mit frischen, saisonalen Zutaten zubereitet. Aenderungen vorbehalten. Bitte informieren Sie uns ueber Allergien und Unvertraeglichkeiten.',
            categories: [
            {
              title: 'Antipasti',
              description: 'Kleine Kostbarkeiten zum Einstimmen',
              items: [
                {
                  name: 'Bruschetta Classica',
                  description: 'Geroestetes Ciabatta mit marinierten San-Marzano-Tomaten, Knoblauch, frischem Basilikum und nativem Olivenoel extra.',
                  price: '12,00 €',
                  image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=900&q=80',
                  tags: ['vegetarisch'],
                  allergens: ['Gluten'],
                },
                {
                  name: 'Carpaccio di Manzo',
                  description: 'Hauchduenn geschnittenes Rinderfilet mit Rucola, Parmigianspänen, Kapern und Zitronendressing.',
                  price: '16,50 €',
                  allergens: ['Milch'],
                },
                {
                  name: 'Burrata Pugliese',
                  description: 'Cremige Burrata aus Apulien auf einem Bett von ofengerosteten Kirschtomaten und Basilikum-Pesto.',
                  price: '15,00 €',
                  image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=900&q=80',
                  tags: ['vegetarisch'],
                  allergens: ['Milch'],
                },
                {
                  name: 'Vitello Tonnato',
                  description: 'Zartes Kalbfleisch in hauchduennen Scheiben mit cremiger Thunfisch-Kapern-Sauce — ein Klassiker aus dem Piemont.',
                  price: '17,50 €',
                  allergens: ['Fisch', 'Ei'],
                },
                {
                  name: 'Cozze alla Marinara',
                  description: 'Frische Miesmuscheln in wuerziger Tomaten-Weisswein-Sauce mit Knoblauch und Petersilie, serviert mit Focaccia.',
                  price: '16,00 €',
                  allergens: ['Weichtiere', 'Gluten'],
                },
                {
                  name: 'Insalata Caprese',
                  description: 'Bueffel-Mozzarella mit sonnengereiften Tomaten, frischem Basilikum und erstklassigem Olivenoel aus Ligurien.',
                  price: '13,50 €',
                  tags: ['vegetarisch'],
                  allergens: ['Milch'],
                },
              ],
            },
            {
              title: 'Primi Piatti — Pasta & Risotto',
              description: 'Taeglich frisch in unserer offenen Kueche zubereitet',
              items: [
                {
                  name: 'Tagliatelle al Tartufo',
                  description: 'Handgerollte Tagliatelle mit schwarzem Trueffel, Parmigiano Reggiano 36 Monate und einem Hauch Trueffeloel.',
                  price: '24,00 €',
                  image: 'https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=900&q=80',
                  tags: ['vegetarisch'],
                  allergens: ['Gluten', 'Milch', 'Ei'],
                },
                {
                  name: 'Risotto ai Funghi Porcini',
                  description: 'Carnaroli-Risotto mit frischen Steinpilzen, Thymian und einem grosszuegigen Stueck Butter zum Abschluss.',
                  price: '21,00 €',
                  tags: ['vegetarisch'],
                  allergens: ['Milch'],
                },
                {
                  name: 'Spaghetti alle Vongole',
                  description: 'Spaghetti mit frischen Venusmuscheln, Knoblauch, Chili, Petersilie und einem Schuss Vermentino.',
                  price: '22,00 €',
                  image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=900&q=80',
                  allergens: ['Gluten', 'Weichtiere'],
                },
                {
                  name: 'Ravioli di Spinaci e Ricotta',
                  description: 'Hausgemachte Ravioli gefuellt mit Spinat und Ricotta in zerlassener Salbeibutter mit Pinienkernen.',
                  price: '19,00 €',
                  tags: ['vegetarisch'],
                  allergens: ['Gluten', 'Milch', 'Ei', 'Nuesse'],
                },
                {
                  name: 'Penne all\'Arrabbiata',
                  description: 'Penne in feuriger Tomatensauce mit Knoblauch, Peperoncino und frischer Petersilie — fuer alle, die es schaerfer moegen.',
                  price: '16,00 €',
                  tags: ['vegetarisch', 'scharf', 'vegan'],
                  allergens: ['Gluten'],
                },
                {
                  name: 'Gnocchi al Gorgonzola',
                  description: 'Kartoffelgnocchi in samtiger Gorgonzola-Sahne-Sauce mit geroesteten Walnuessen und frischem Schnittlauch.',
                  price: '18,50 €',
                  tags: ['vegetarisch'],
                  allergens: ['Gluten', 'Milch', 'Nuesse'],
                },
              ],
            },
            {
              title: 'Secondi — Hauptgerichte',
              description: 'Fleisch & Fisch aus nachhaltiger Herkunft',
              items: [
                {
                  name: 'Osso Buco alla Milanese',
                  description: 'Langsam geschmorte Kalbshaxe auf Safranrisotto mit Gremolata — unser Signature-Gericht seit 1998.',
                  price: '34,00 €',
                  image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=80',
                  allergens: ['Milch'],
                },
                {
                  name: 'Saltimbocca alla Romana',
                  description: 'Zartes Kalbsschnitzel mit luftgetrocknetem Prosciutto und Salbei, abgeloescht mit Marsala, dazu Blattspinat.',
                  price: '29,00 €',
                  allergens: ['Milch'],
                },
                {
                  name: 'Branzino al Forno',
                  description: 'Ganzer Wolfsbarsch im Ofen gegart mit Kirschtomaten, Oliven, Kapern und frischen Kraeutern.',
                  price: '32,00 €',
                  image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=900&q=80',
                  allergens: ['Fisch'],
                },
                {
                  name: 'Tagliata di Manzo',
                  description: 'Gegrilltes Rinderrueckensteak, aufgeschnitten auf Rucola-Bett mit Parmesan, Balsamico-Reduktion und Rosmarin-Kartoffeln.',
                  price: '38,00 €',
                  allergens: ['Milch'],
                },
                {
                  name: 'Scaloppine al Limone',
                  description: 'Duenne Kalbsschnitzel in frischer Zitronen-Butter-Sauce mit Kapern, dazu saisonales Gemuese.',
                  price: '28,00 €',
                  allergens: ['Milch'],
                },
              ],
            },
            {
              title: 'Dolci',
              description: 'Suesse Verfuehrungen zum perfekten Abschluss',
              items: [
                {
                  name: 'Tiramisù della Casa',
                  description: 'Unser legendaeres Hausdessert nach Nonna Marias Rezept — Mascarpone, Espresso, Amaretto, 24 Stunden durchgezogen.',
                  price: '12,00 €',
                  image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&q=80',
                  allergens: ['Milch', 'Ei', 'Gluten'],
                },
                {
                  name: 'Panna Cotta ai Frutti di Bosco',
                  description: 'Vanille-Panna-Cotta mit hausgemachtem Waldbeeren-Coulis und frischer Minze.',
                  price: '10,00 €',
                  tags: ['vegetarisch'],
                  allergens: ['Milch'],
                },
                {
                  name: 'Affogato al Caffè',
                  description: 'Cremiges Fior-di-Latte-Gelato, uebergossen mit einem doppelten Espresso und optional einem Schuss Amaretto.',
                  price: '9,50 €',
                  tags: ['vegetarisch'],
                  allergens: ['Milch'],
                },
                {
                  name: 'Cannoli Siciliani',
                  description: 'Knusprige Teigroellchen gefuellt mit suesser Ricotta-Creme, kandierten Fruechten und Pistazien aus Bronte.',
                  price: '13,00 €',
                  image: 'https://images.unsplash.com/photo-1611293388250-580b08c4a145?w=900&q=80',
                  allergens: ['Gluten', 'Milch', 'Nuesse'],
                },
              ],
            },
          ],
          },
        },
      ],
    },
    {
      slug: 'ambiente',
      title: 'Ambiente & Raeume',
      sections: [
        {
          ...HERO,
          id: 'rs-amb-hero',
          type: 'hero',
          data: {
            headline: 'Ambiente & Raeume',
            subline: 'Wo Geschichte auf Genuss trifft — unser Restaurant in der Innsbrucker Altstadt',
            bgImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=1800&q=85',
          },
        },
        {
          ...B,
          id: 'rs-amb-detail',
          type: 'ambience',
          data: {
            headline: 'Unsere Raeumlichkeiten',
            subline: 'Drei einzigartige Bereiche fuer unvergessliche Momente',
            imagePrimary: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=900&q=80',
            imageSecondary: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=900&q=80',
            imageTertiary: 'https://images.unsplash.com/photo-1528823872057-9c018a7a7553?w=900&q=80',
            highlights: [
              {
                title: 'Gewoelbekeller aus dem 15. Jahrhundert',
                text: 'Originale Steinboegen und historisches Ambiente verleihen jedem Besuch einen besonderen Rahmen.',
                icon: 'castle',
              },
              {
                title: 'Sonnenterrasse mit Alpenblick',
                text: 'Geniessen Sie von Mai bis September die warme Jahreszeit mit Blick auf die Innsbrucker Nordkette.',
                icon: 'sun',
              },
              {
                title: 'Private Dining fuer bis zu 12 Personen',
                text: 'Unser Weinkeller bietet den perfekten Rahmen fuer Geburtstage, Jubilaeen oder Geschaeftsessen in exklusiver Atmosphaere.',
                icon: 'wine',
              },
            ],
            ctaPrimary: { label: 'Tisch reservieren', href: '/demo/restaurant/reservierung' },
          },
        },
      ],
    },
    {
      slug: 'events',
      title: 'Events & Catering',
      sections: [
        {
          ...HERO,
          id: 'rs-evt-hero',
          type: 'hero',
          data: {
            headline: 'Events & Catering',
            subline: 'Gemeinsam feiern, geniessen und die italienische Kueche erleben',
            bgImage: 'https://images.unsplash.com/photo-1530062845289-9109b2c9c868?w=1800&q=85',
          },
        },
        {
          ...B,
          id: 'rs-evt-list',
          type: 'events',
          data: {
            headline: 'Unsere Veranstaltungen',
            subline: 'Regelmaessige Events und individuelle Angebote',
            events: [
            {
              title: 'Wein & Pasta Abend',
              dateLabel: 'Jeden letzten Freitag im Monat',
              timeLabel: '19:00 — 22:30 Uhr',
              description: 'Vier Gaenge, vier Weine: Unser Sommelier Andrea fuehrt Sie durch eine Reise von Suedtirol bis Sizilien. Jeder Gang wird von Kuechenchef Marco live erklaert und mit dem perfekten Wein begleitet. Inkl. Aperitivo, Wasser und Kaffee.',
              image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=900&q=80',
              imageAlt: 'Weinglaeser und Pasta auf einem festlich gedeckten Tisch',
              priceLabel: '49,00 € pro Person',
              cta: { label: 'Platz reservieren', href: '/demo/restaurant/reservierung' },
            },
            {
              title: 'Kochkurs: Frische Pasta',
              dateLabel: 'Jeden 2. und 4. Samstag im Monat',
              timeLabel: '10:00 — 14:00 Uhr',
              description: 'Lernen Sie von Kuechenchef Marco die Kunst der frischen Pasta: Tagliatelle, Ravioli und Gnocchi — von Hand gemacht, mit Liebe und den besten Zutaten. Inkl. gemeinsames Mittagessen mit Wein und Rezeptmappe zum Mitnehmen.',
              image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=900&q=80',
              imageAlt: 'Haende formen frische Pasta auf einer bemehlten Arbeitsflaeche',
              priceLabel: '89,00 € pro Person',
              cta: { label: 'Kurs buchen', href: '/demo/restaurant/reservierung' },
            },
            {
              title: 'Firmen-Events & Private Dining',
              dateLabel: 'Auf Anfrage',
              timeLabel: 'Individuell planbar',
              description: 'Ob Teambuilding, Kundenevent oder private Feier — wir gestalten Ihr Event nach Ihren Wuenschen. Exklusiver Weinkeller fuer bis zu 12 Personen, Hauptsaal fuer Gruppen bis 60 Personen. Individuelle Menuezusammenstellung, Weinbegleitung und Dekoration auf Anfrage.',
              image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=900&q=80',
              imageAlt: 'Elegantes Private Dining im Weinkeller',
              priceLabel: 'Auf Anfrage',
              cta: { label: 'Anfrage senden', href: '/demo/restaurant/reservierung' },
            },
          ],
          },
        },
      ],
    },
    {
      slug: 'reservierung',
      title: 'Reservierung',
      sections: [
        {
          ...HERO,
          id: 'rs-res-hero',
          type: 'hero',
          data: {
            headline: 'Reservierung',
            subline: 'Sichern Sie sich Ihren Lieblingstisch in der Trattoria Dal Maestro',
            bgImage: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=1800&q=85',
            primaryCta: { label: 'Jetzt reservieren', href: '#reservation-form' },
          },
        },
        {
          ...B,
          id: 'rs-res-hours',
          type: 'openingHours',
          data: {
            headline: 'Unsere Oeffnungszeiten',
            days: [
              { label: 'Dienstag — Samstag', hours: '11:30 — 14:30 Uhr & 17:30 — 23:00 Uhr' },
              { label: 'Sonntag', hours: '11:30 — 22:00 Uhr' },
              { label: 'Montag', hours: '', closed: true, note: 'Ruhetag' },
            ],
            kitchenHoursHeadline: 'Kuechenzeiten',
            kitchenHoursText: 'Warme Kueche bis 30 Minuten vor Restaurantschluss.',
            holidayNote: 'An Feiertagen nach gesonderter Ankuendigung.',
            ctaPrimary: { label: 'Tisch reservieren', href: '/demo/restaurant/reservierung' },
          },
        },
        {
          ...B,
          id: 'rs-res-form',
          type: 'reservation',
          data: {
            headline: 'Tisch reservieren',
            introText: 'Fuellen Sie einfach das Formular aus und wir bestaetigen Ihre Reservierung innerhalb von 2 Stunden per E-Mail. Fuer kurzfristige Anfragen empfehlen wir einen Anruf.',
            partySizeOptions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            phoneCta: {
              label: 'Telefonisch: +43 512 123 456',
              href: 'tel:+43512123456',
            },
            timeHint: 'Bitte beachten Sie: Reservierungen fuer Freitag und Samstag ab 19 Uhr sind besonders beliebt. Wir empfehlen eine Buchung mindestens 3 Tage im Voraus.',
            policyText: 'Bitte informieren Sie uns mindestens 24 Stunden im Voraus, falls Sie Ihre Reservierung stornieren oder aendern moechten. Bei Nichterscheinen kann eine Gebuehr von 25,00 € pro Person anfallen. Gruppen ab 8 Personen bitten wir um eine Anzahlung.',
            externalBookingCta: {
              label: 'Oder buchen Sie ueber OpenTable',
              href: '/demo/restaurant/reservierung',
            },
            submitLabel: 'Reservierung absenden',
          },
        },
      ],
    },
  ],
};
